import type {
  FortuneCategory,
  FortuneRarity,
  FortuneTier,
  OmamoriRouteConfig,
  OmamoriRouteId,
  OmamoriSettings,
  RitualAssetSet,
  SceneCandidate,
} from "@/types/omikuji";

export const CATEGORY_LABELS: Record<FortuneCategory, string> = {
  study: "学习运",
  love: "感情运",
  slacking: "摸鱼运",
  lateNight: "熬夜运",
  social: "社恐出门运",
  wealth: "财富运",
  hidden: "隐藏稀有签",
};

export const TIER_LABELS: Record<FortuneTier, string> = {
  "small-blessing": "小吉",
  "middle-blessing": "中吉",
  "great-blessing": "大吉",
  shadow: "夜相",
  secret: "秘签",
};

export const RARITY_LABELS: Record<FortuneRarity, string> = {
  common: "常驻",
  uncommon: "微稀有",
  rare: "稀有",
  epic: "高稀有",
  legendary: "传说",
};

export const FORTUNE_RARITY_WEIGHTS: Record<FortuneRarity, number> = {
  common: 58,
  uncommon: 24,
  rare: 10,
  epic: 5,
  legendary: 2,
};

export const CATEGORY_DRAW_MODIFIER: Record<FortuneCategory, number> = {
  study: 1,
  love: 1,
  slacking: 0.94,
  lateNight: 0.9,
  social: 0.95,
  wealth: 0.75,
  hidden: 0.18,
};

export const DEFAULT_SETTINGS: OmamoriSettings = {
  ambienceEnabled: true,
  sfxEnabled: true,
  ambienceVolume: 0.4,
  sfxVolume: 0.7,
  reduceMotion: false,
  defaultRouteId: "hakurei",
  askRouteOnLaunch: true,
};

export const OMAMORI_ROUTE_IDS: OmamoriRouteId[] = [
  "hakurei",
  "scarlet",
  "eientei",
  "moriya-shrine",
  "hakugyokurou",
  "forest-of-magic",
  "myouren-temple",
  "palace-of-earth-spirits",
  "sanzu-river",
  "misty-lake",
  "human-village",
  "sunflower-field",
  "divine-spirit-mausoleum",
  "nameless-hill",
];

function imageFormatForBucket(): "webp" {
  return "webp";
}

function imageBaseForBucket(bucket: "active" | "expanded"): string {
  return `/images/optimized/generated-themes/${bucket}`;
}

function buildRitualAssets(bucket: "active" | "expanded", sceneId: string): RitualAssetSet {
  const base = `${imageBaseForBucket(bucket)}/rituals/${sceneId}`;
  const sourceBase = `/images/generated-themes/${bucket}/rituals/${sceneId}`;
  const format = imageFormatForBucket();

  return {
    ritualBase: `${base}/ritual-base.${format}`,
    paperClosed: `${base}/paper-closed.${format}`,
    paperEmerging: `${base}/paper-emerging.${format}`,
    paperOpen: `${base}/paper-open.${format}`,
    fxParticles: `${base}/fx-particles.${format}`,
    fxReveal: `${base}/fx-reveal.${format}`,
    resultCorner: `${base}/result-corner.${format}`,
    sourceSheet: `${sourceBase}/source-sheet-v1.png`,
  };
}

const ROUTE_RITUAL_PROFILES = {
  hakurei: {
    ritualType: "参拜式",
    paper: "朱白御札纸签",
    tool: "铃绳、赛钱箱、旧木签匣",
    sound: "神乐铃、木匣轻撞、结界回声",
    verbs: ["摇铃", "纳声", "翻签", "收束"],
  },
  scarlet: {
    ritualType: "茶会式",
    paper: "玫瑰茶笺",
    tool: "银托盘、红茶杯、窗纱、怀表",
    sound: "茶匙轻碰、银托盘滑响、窗纱风声",
    verbs: ["递呈", "停盘", "遮句", "翻笺"],
  },
  eientei: {
    ritualType: "问药式",
    paper: "月下药方签",
    tool: "药签匣、药包、竹影纸门",
    sound: "药匣细响、月兔脚步、竹叶沙声",
    verbs: ["问诊", "称量", "配签", "封药"],
  },
  "moriya-shrine": {
    ritualType: "风祝式",
    paper: "淡绿卷轴神签",
    tool: "风祝铃、注连绳、纸垂、卷轴签架",
    sound: "高山风、风祝铃、远处太鼓",
    verbs: ["招风", "卷轴", "托起", "降签"],
  },
  hakugyokurou: {
    ritualType: "幽冥式",
    paper: "半透明冥签",
    tool: "樱庭签台、石阶、佩刀冷光",
    sound: "风铃、樱瓣落声、剑鞘轻响",
    verbs: ["落樱", "映刀", "缓显", "寄回"],
  },
  "forest-of-magic": {
    ritualType: "魔导式",
    paper: "淡紫星屑纸符",
    tool: "魔导书、蘑菇灯、玻璃瓶",
    sound: "书页翻动、玻璃细响、魔力嗡鸣",
    verbs: ["翻页", "点粉", "浮符", "试写"],
  },
  "myouren-temple": {
    ritualType: "寺院式",
    paper: "莲纹寺签",
    tool: "经卷签台、寺院灯、木鱼",
    sound: "木鱼轻敲、经卷展开、夜风诵读",
    verbs: ["点灯", "摊卷", "敲木", "安放"],
  },
  "palace-of-earth-spirits": {
    ritualType: "心读式",
    paper: "暗红紫心签",
    tool: "第三只眼签匣、透光方砖、旧地狱余火",
    sound: "地热低鸣、炉火余声、怨灵轻鸣",
    verbs: ["读心", "透火", "闭眼", "显影"],
  },
  "sanzu-river": {
    ritualType: "渡河式",
    paper: "灰蓝河雾短签",
    tool: "渡船签盒、旧船桨、摆渡钱",
    sound: "船桨拨水、摆渡钱轻碰、无风河雾",
    verbs: ["拨雾", "靠岸", "换钱", "渡句"],
  },
  "misty-lake": {
    ritualType: "冰雾式",
    paper: "浅蓝半透明短签",
    tool: "浅木托盘、薄冰、水纹、妖精光点",
    sound: "湖水轻拍、冰晶细碎、光点掠声",
    verbs: ["结冰", "推纹", "浮签", "照亮"],
  },
  "human-village": {
    ritualType: "街巷式",
    paper: "米白账册短签",
    tool: "木抽屉、灯笼、账册、布告",
    sound: "抽屉滑动、店招轻响、远处寒暄",
    verbs: ["开屉", "照纸", "记账", "递话"],
  },
  "sunflower-field": {
    ritualType: "季节异变式",
    paper: "淡金季节签",
    tool: "旧木牌、小签箱、阳伞、花瓣影",
    sound: "夏风穿花、木牌轻响、伞柄碰箱",
    verbs: ["晒亮", "错影", "升瓣", "转向"],
  },
  "divine-spirit-mausoleum": {
    ritualType: "道场式",
    paper: "青白道符灵签",
    tool: "供案、玉笏、铜铃、八角光阵",
    sound: "细铜铃、石阶回音、香火轻响",
    verbs: ["归位", "敲铃", "立符", "点阵"],
  },
  "nameless-hill": {
    ritualType: "遗忘式",
    paper: "灰白无名短签",
    tool: "无标签玻璃瓶、褪色细绳、铃兰影",
    sound: "玻璃轻碰、草叶细响、低低耳鸣",
    verbs: ["开瓶", "回收", "显名", "静置"],
  },
} satisfies Record<OmamoriRouteId, OmamoriRouteConfig["ritualProfile"]>;

const BASE_OMAMORI_ROUTES = {
  hakurei: {
    id: "hakurei",
    label: "博丽神社",
    shortLabel: "神社",
    subtitle: "先在结界边缘停一停",
    description:
      "朱红鸟居与旧白墙把夜色压低。铃声穿过结界，今日的签纸会从旧木匣里醒来。",
    cardDescription: "铃声穿过结界，今日的签纸会从旧木匣里醒来。",
    cornerLabel: "正统神社签",
    enterLabel: "前往神社参拜",
    drawLabel: "抽取今日签文",
    revisitLabel: "展开今日签文",
    backLabel: "重新选择入口",
    statusIdle: "今日尚未参拜",
    resultTitle: "今日签文",
    shareFrom: "博丽神社",
    sceneImage: "/images/optimized/generated-themes/active/hakurei-scene.webp",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/ofuda-field.svg",
    stageOverlayImage: "/images/generated-themes/active/hakurei-stage-props.svg",
    ritualImage: "/images/optimized/generated-themes/active/rituals/hakurei-ritual-kit-v1.webp",
    ritualAssets: buildRitualAssets("active", "hakurei"),
    textTone: "shrine",
    visual: {
      ink: "#f8efe7",
      accent: "#d94b4b",
      secondary: "#d8b15f",
      shadow: "rgba(89, 16, 22, 0.42)",
      surface: "rgba(42, 15, 18, 0.72)",
      glow: "rgba(217, 75, 75, 0.34)",
      particle: "rgba(248, 239, 231, 0.42)",
    },
    copyLabels: {
      heading: "博丽参拜签",
      quote: "结界所示",
      summary: "参拜签意",
      advice: "神社一句",
      luckyColor: "今日鸟居色",
      luckyItem: "随身御札",
      motif: "朱白结界纹",
      rare: "赛钱箱异响",
      channel: "博丽签路",
      inspiration: "社务所旁注",
    },
    stage: {
      eyebrow: "今夜参拜",
      title: "铃响之后，今日签文会从纸尘里展开",
      description:
        "轻触铃绳，等结界的回声沉下来。铃音会在第一次点击后唤起，随后陪着签纸展开。",
      ringing: "神乐铃正在把结界声纳进纸签",
      shaking: "旧木匣里有朱白御札轻轻相撞",
      revealing: "纸尘落下，博丽参拜签正翻到正面",
      rareNotice: "赛钱箱异响已出现",
      favoriteAdded: "已收进本地签册",
      favoriteRemoved: "已把这张签文放回神社回声里",
    },
    copyTone: "hakurei",
    ritualProfile: ROUTE_RITUAL_PROFILES.hakurei,
  },
  scarlet: {
    id: "scarlet",
    label: "红魔馆",
    shortLabel: "红魔馆",
    subtitle: "湖畔洋馆的茶会已经备好",
    description:
      "雾之湖的水光照亮红砖洋馆。玫瑰、蝙蝠剪影和红茶香气一起，把今日签意递到银托盘上。",
    cardDescription: "玫瑰与红茶香会把今日签意送到窗边。",
    cornerLabel: "洋馆茶会",
    enterLabel: "走向湖畔红馆",
    drawLabel: "开启红茶占签",
    revisitLabel: "重读茶会签笺",
    backLabel: "更换入口",
    statusIdle: "今日尚未赴约",
    resultTitle: "红馆茶会签",
    shareFrom: "红魔馆",
    sceneImage: "/images/optimized/generated-themes/active/scarlet-scene.webp",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/scarlet-roses.svg",
    stageOverlayImage: "/images/generated-themes/active/scarlet-stage-props.svg",
    ritualImage: "/images/optimized/generated-themes/active/rituals/scarlet-ritual-kit-v1.webp",
    ritualAssets: buildRitualAssets("active", "scarlet"),
    textTone: "mansion",
    visual: {
      ink: "#fff8f6",
      accent: "#e84f72",
      secondary: "#8fc5ff",
      shadow: "rgba(200, 64, 90, 0.2)",
      surface: "rgba(255, 238, 242, 0.78)",
      glow: "rgba(255, 128, 154, 0.34)",
      particle: "rgba(255, 237, 244, 0.72)",
    },
    copyLabels: {
      heading: "红馆茶会签",
      quote: "银盘所示",
      summary: "茶笺签意",
      advice: "馆中评语",
      luckyColor: "今日茶色",
      luckyItem: "随身点心",
      motif: "玫瑰纹章",
      rare: "怀表停拍",
      channel: "茶会频道",
      inspiration: "窗纱旁注",
    },
    stage: {
      eyebrow: "湖畔茶会",
      title: "银托盘轻响，今日签笺会从玫瑰旁展开",
      description:
        "轻触红茶铃，等湖风掀起窗纱。红魔馆的签笺会带着一点优雅和一点任性出现。",
      ringing: "茶匙轻碰杯沿，洋馆回廊被唤醒",
      shaking: "银托盘停在窗纱边，红茶热气遮住半句答案",
      revealing: "玫瑰茶笺正被怀表声翻开",
      rareNotice: "怀表停拍已出现",
      favoriteAdded: "已收进本地茶会册",
      favoriteRemoved: "已把这张签笺放回红馆窗边",
    },
    copyTone: "scarlet",
    ritualProfile: ROUTE_RITUAL_PROFILES.scarlet,
  },
  eientei: {
    id: "eientei",
    label: "永远亭",
    shortLabel: "永远亭",
    subtitle: "迷途竹林里，月光正落在纸门上",
    description:
      "竹叶筛下柔亮月色，白兔脚步在廊下轻轻跑过。药师的纸札与月都的微光，会把今日建议写得更清楚。",
    cardDescription: "竹叶、月光与纸门上的微光，会把今日建议收进一枚温柔签里。",
    cornerLabel: "月下药签",
    enterLabel: "走入迷途竹林",
    drawLabel: "抽取月下药签",
    revisitLabel: "展开月下药签",
    backLabel: "重选入口",
    statusIdle: "今日尚未问药",
    resultTitle: "永远亭月签",
    shareFrom: "永远亭",
    sceneImage: "/images/optimized/generated-themes/active/eientei-scene.webp",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/eientei-bamboo.svg",
    stageOverlayImage: "/images/generated-themes/active/eientei-stage-props.svg",
    ritualImage: "/images/optimized/generated-themes/active/rituals/eientei-ritual-kit-v1.webp",
    ritualAssets: buildRitualAssets("active", "eientei"),
    textTone: "moon",
    visual: {
      ink: "#f7fff7",
      accent: "#65b987",
      secondary: "#d6b8ff",
      shadow: "rgba(74, 143, 108, 0.2)",
      surface: "rgba(236, 255, 239, 0.78)",
      glow: "rgba(126, 204, 151, 0.3)",
      particle: "rgba(246, 255, 246, 0.78)",
    },
    copyLabels: {
      heading: "永远亭月签",
      quote: "药方所示",
      summary: "药方签意",
      advice: "问诊小方",
      luckyColor: "今日月色",
      luckyItem: "随身药包",
      motif: "竹影方格",
      rare: "月兔急步",
      channel: "药签频道",
      inspiration: "纸门旁注",
    },
    stage: {
      eyebrow: "竹林问药",
      title: "月兔跑过回廊，药签从竹影里亮起来",
      description:
        "轻触月铃，让竹叶的沙沙声慢下来。永远亭会给今天配一份温柔但不含糊的建议。",
      ringing: "月铃穿过纸门，月兔脚步停了一瞬",
      shaking: "药签匣正在称量今日的方子",
      revealing: "月下药方签正从竹影里滑出",
      rareNotice: "月兔急步已出现",
      favoriteAdded: "已收进本地月签册",
      favoriteRemoved: "已把这张药签放回竹林月色里",
    },
    copyTone: "eientei",
    ritualProfile: ROUTE_RITUAL_PROFILES.eientei,
  },
} satisfies Record<"hakurei" | "scarlet" | "eientei", OmamoriRouteConfig>;

const BASE_OMAMORI_ROUTE_LIST = Object.values(BASE_OMAMORI_ROUTES);

const ACTIVE_SCENE_CANDIDATES: SceneCandidate[] = BASE_OMAMORI_ROUTE_LIST.map((route) => ({
  id: route.id,
  label: route.label,
  subtitle: route.subtitle,
  status: "active",
  sceneImage: route.sceneImage,
  ritualImage: route.ritualImage,
  ritualAssets: route.ritualAssets,
  routeId: route.id,
  description: route.description,
  cardDescription: route.cardDescription,
  cornerLabel: route.cornerLabel,
  animationPlan: route.stage.title,
  visual: route.visual,
}));

const SCENE_BLUEPRINTS: SceneCandidate[] = [
  ...ACTIVE_SCENE_CANDIDATES,
  {
    id: "moriya-shrine",
    label: "守矢神社",
    subtitle: "山风从注连绳下穿过",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/moriya-shrine-scene.webp",
    ritualAssets: buildRitualAssets("expanded", "moriya-shrine"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/moriya-shrine-ritual-kit-v1.webp",
    description: "风从妖怪之山的参道卷下来，纸垂在注连绳下轻轻打结。守矢的铃声比山脚更亮，签纸会带着一点奇迹的余温落到掌心。",
    cardDescription: "山风掠过注连绳，卷轴签在风祝铃声里展开。",
    cornerLabel: "山上风祝签",
    animationPlan: "山风卷轴签",
    ritualPlan: {
      tool: "风祝铃与注连绳签架：以山中神社的参拜铃为核心，铃柄带纸垂与御柱感木纹。",
      paper: "细长神签卷轴：淡绿和白色和纸，边缘有风纹、蛙纹与蛇形注连纹压印。",
      reveal: "山风卷开签轴：铃响后纸垂先摆动，卷轴被风托起，再从中心向两侧展开。",
      ambientMotion: "高空云影、纸垂摆动、叶片沿对角线掠过，偶尔出现奇迹粒子沿注连绳滑动。",
      sound: "清脆神乐铃、山风穿过树梢、远处祭典太鼓的低频点缀，整体比博丽神社更开阔。",
      assetPrompt:
        "明亮日式二次元游戏资产，一组守矢神社风祝抽签仪式道具：风祝铃、注连绳签架、淡绿白色神签卷轴、纸垂、山风叶片与奇迹粒子，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：守矢神社位于妖怪之山，是东方风神录相关场景。",
      "THBWiki / Touhou Wiki：东风谷早苗是守矢神社风祝，关联奇迹与神事语境。",
      "THBWiki / Touhou Wiki：八坂神奈子、洩矢诹访子与守矢神社信仰体系相关，可转化为注连绳、蛇/蛙纹样与山神氛围。",
    ],
    visual: {
      ink: "#f8fff4",
      accent: "#58a66d",
      secondary: "#b8d96a",
      shadow: "rgba(38, 92, 58, 0.34)",
      surface: "rgba(231, 250, 225, 0.74)",
      glow: "rgba(120, 202, 127, 0.34)",
      particle: "rgba(238, 255, 225, 0.72)",
    },
  },
  {
    id: "hakugyokurou",
    label: "白玉楼",
    subtitle: "樱庭尽头的冥界回廊",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/hakugyokurou-scene.webp",
    ritualAssets: buildRitualAssets("expanded", "hakugyokurou"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/hakugyokurou-ritual-kit-v1.webp",
    description: "樱花落到石阶上，没有急着融进冥界的雾里。白玉楼的签纸很轻，像被庭师的刀光翻过一面，慢慢露出今日该记住的话。",
    cardDescription: "半透明冥签被樱瓣托起，冷色刀光扫过纸面。",
    cornerLabel: "幽冥樱签",
    animationPlan: "樱庭冥签",
    ritualPlan: {
      tool: "樱庭签台：带细雕栏板与石阶底座的白木签台，边缘挂薄樱花穗。",
      paper: "半透明冥签：薄樱粉与银白相间的和纸，纸面隐约透出庭院樱枝与月影。",
      reveal: "刀光映签：拔刀的冷光先扫过纸面，再由花瓣飘落遮住文字，最后缓慢显形。",
      ambientMotion: "樱花逆风旋转、薄雾沿石阶缓行、纸面有轻微发光波纹，整体安静但不死寂。",
      sound: "竹笛、远处风铃、剑鞘轻响和低沉回音，声音比守矢更柔，更空。",
      assetPrompt:
        "明亮日式二次元游戏资产，一组白玉楼幽冥抽签仪式道具：樱庭签台、半透明冥签、佩刀冷光、樱花花瓣、薄雾与石阶元素，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：白玉楼是与冥界、庭院、樱花意象相关的重要场景。",
      "THBWiki / Touhou Wiki：西行寺幽幽子与白玉楼、樱花庭院的意象高度绑定。",
      "THBWiki / Touhou Wiki：魂魄妖梦与刀、庭院守卫语境相关，可转化为刀光揭签的仪式方式。",
    ],
    visual: {
      ink: "#fff7fb",
      accent: "#e785b2",
      secondary: "#cbb8ff",
      shadow: "rgba(126, 61, 105, 0.3)",
      surface: "rgba(255, 238, 247, 0.76)",
      glow: "rgba(239, 145, 190, 0.34)",
      particle: "rgba(255, 243, 249, 0.78)",
    },
  },
  {
    id: "forest-of-magic",
    label: "魔法森林",
    subtitle: "星屑藏在蘑菇伞影里",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/forest-of-magic-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "forest-of-magic"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/forest-of-magic-ritual-kit-v1.webp",
    description: "树根旁的旧魔导书自己翻了一页，蘑菇灯在潮气里亮一下又暗下去。森林里的签文不太守规矩，星屑会先跑到纸边，再把答案推出来。",
    cardDescription: "魔导书翻到空白页，星屑纸符从页缝里浮起。",
    cornerLabel: "森林魔导签",
    animationPlan: "星屑纸符",
    ritualPlan: {
      tool: "蘑菇魔导书台：一本半开的旧魔法书压在树根上，旁边只有两三枚发光蘑菇和小玻璃瓶。",
      paper: "星屑纸符：淡紫短符纸，边缘有少量星粉和蘑菇孢子点，不做复杂符文墙。",
      reveal: "书页翻风揭签：魔法书自动翻到空白页，纸符从页缝里浮起，星屑沿纸边点亮签意。",
      ambientMotion: "孢子光点慢慢上浮，树影遮住又露出纸符，偶尔有一枚蘑菇像小灯一样亮一下。",
      sound: "纸页轻翻、玻璃瓶细响、低低的魔力嗡鸣和远处树叶声，整体阴湿但带一点好奇心。",
      assetPrompt:
        "明亮日式二次元游戏资产，魔法森林抽签仪式道具：树根上的半开旧魔法书、两三枚发光蘑菇、小玻璃瓶、淡紫星屑纸符、少量漂浮孢子光点。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：魔法森林是幻想乡中阴暗潮湿的原始森林，妖怪蘑菇孢子与瘴气使其不适合人类居住。",
      "THBWiki：魔法森林中住着雾雨魔理沙、爱丽丝等魔法使，蘑菇也与提升魔力的设定相关。",
      "THBWiki：森林内有香霖堂、废弃洋馆、信号塔等边缘物件，后续素材可保留少量旧物感但不要堆满杂物。",
    ],
    visual: {
      ink: "#f7f6ff",
      accent: "#8d78dc",
      secondary: "#f2c85e",
      shadow: "rgba(66, 50, 120, 0.32)",
      surface: "rgba(239, 235, 255, 0.76)",
      glow: "rgba(147, 126, 220, 0.34)",
      particle: "rgba(255, 247, 205, 0.72)",
    },
  },
  {
    id: "myouren-temple",
    label: "命莲寺",
    subtitle: "莲纹灯影沿着寺廊铺开",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/myouren-temple-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "myouren-temple"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/myouren-temple-ritual-kit-v1.webp",
    description: "寺灯沿着参拜道慢慢亮起，木鱼声落在夜风里。命莲寺的签不催人，它先把经卷摊平，再让莲纹从纸角浮出来。",
    cardDescription: "寺灯照着经卷签台，莲纹短签安静滑出。",
    cornerLabel: "莲灯寺签",
    animationPlan: "莲纹经卷签",
    ritualPlan: {
      tool: "莲纹经卷签台：青石参拜道旁的小经卷台，配一盏寺院灯和一只朴素木鱼。",
      paper: "莲纹寺签：暖白短签纸，边缘压莲纹，背面只留一条像经卷轴心的细线。",
      reveal: "经卷展开揭签：寺灯先亮，经卷慢慢展开，莲纹纸签从卷轴内侧滑出并停在木鱼旁。",
      ambientMotion: "石灯笼微光、樱花瓣少量落下、参拜道远处有夜间妖怪法会的模糊灯影。",
      sound: "木鱼轻敲、经卷纸面展开、石灯笼旁的夜风和远处低声诵读，稳重但不沉闷。",
      assetPrompt:
        "明亮日式二次元游戏资产，命莲寺抽签仪式道具：青石参拜道、小经卷台、暖色寺院灯、朴素木鱼、莲纹短签纸、少量樱花瓣。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：命莲寺由圣白莲建立，位于人类村落外，是以妖怪修行为重要语境的寺庙。",
      "THBWiki：命莲寺包含山门、正殿、钟楼、参拜道、石灯笼和墓地，正殿前有青色砖石参拜道。",
      "THBWiki：命莲寺白天安静庄严，夜晚因妖怪寄居和法会语境变得热闹，可转化为远处灯影和低声诵读。",
    ],
    visual: {
      ink: "#fffaf0",
      accent: "#d18c46",
      secondary: "#7fb6d8",
      shadow: "rgba(126, 72, 36, 0.3)",
      surface: "rgba(255, 244, 223, 0.78)",
      glow: "rgba(225, 156, 83, 0.34)",
      particle: "rgba(255, 248, 230, 0.74)",
    },
  },
  {
    id: "palace-of-earth-spirits",
    label: "地灵殿",
    subtitle: "旧地狱的地砖下，余火还在看人心",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/palace-of-earth-spirits-scene-v3.webp",
    ritualAssets: buildRitualAssets("expanded", "palace-of-earth-spirits"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/palace-of-earth-spirits-ritual-kit-v1.webp",
    description: "旧地狱的热从地砖下透上来，房间深处安静得像有人刚读完你的心。第三只眼的纹样轻轻张开，签意从余火里浮出。",
    cardDescription: "透光方砖忽明忽暗，心读签匣在旧地狱余火里醒来。",
    cornerLabel: "地底心签",
    animationPlan: "心读余火签",
    ritualPlan: {
      tool: "心读签匣：素黑木匣配一个简洁第三只眼纹样，旁边只留一枚小鸟纹地砖作识别。",
      paper: "地底心签：暗红紫和纸，边缘略暖，纸背用少量方砖光影暗示旧地狱。",
      reveal: "读心显影：签纸先浮出模糊心音，第三只眼纹样轻轻闭合又张开，文字像从地砖下的余火里透上来。",
      ambientMotion: "少量透光方砖忽明忽暗，两三点怨灵光贴地游动，房间深处传来无访客的空回声。",
      sound: "低频地热、远处炉火、怨灵轻鸣和轻微木地板声，整体封闭、向内、略带压迫感。",
      assetPrompt:
        "干净日式二次元游戏背景，风格与现有 generated-themes 场景保持一致：地灵殿封闭室内大堂、简单柱廊、方砖地面、少量透光地砖、旧地狱余火、两三处怨灵光点、一个素黑心读签匣与第三只眼纹样。少道具、少纹理、低复杂度、可放 UI 文案。无角色，无文字，不要红魔馆外景，不要地狱城堡，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：地灵殿位于旧地狱中心，是古明地觉居住的大型洋馆，其下方为灼热地狱遗址与核聚变炉。",
      "THBWiki：地灵殿因读心能力几乎没有访客，但有大量宠物、怨灵管理语境。",
      "THBWiki：地灵殿四面有深浅交错方砖和彩色透光砖，图案疑似取自八咫乌，后续图要优先使用室内地砖与余火而非外部城堡。",
    ],
    visual: {
      ink: "#fff0ec",
      accent: "#b74758",
      secondary: "#7e63b8",
      shadow: "rgba(51, 26, 48, 0.42)",
      surface: "rgba(58, 32, 53, 0.68)",
      glow: "rgba(210, 72, 88, 0.3)",
      particle: "rgba(244, 190, 208, 0.68)",
    },
  },
  {
    id: "sanzu-river",
    label: "三途川",
    subtitle: "河雾从彼岸花边升起",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/sanzu-river-scene.webp",
    ritualAssets: buildRitualAssets("expanded", "sanzu-river"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/sanzu-river-ritual-kit-v1.webp",
    description: "河上没有风，只有船桨把雾轻轻拨开。三途川的签纸先映在水面，再从船沿浮起，像一枚被摆渡钱换来的提醒。",
    cardDescription: "渡船签盒贴着河雾，灰蓝短签从水影里靠岸。",
    cornerLabel: "渡河雾签",
    animationPlan: "河雾渡签",
    ritualPlan: {
      tool: "渡船签盒：一只朴素小木盒放在无帆渡船边，旁边是一枚旧船桨和几枚摆渡钱。",
      paper: "河雾渡签：灰蓝短签纸，纸面像被河雾润湿，边缘有彼岸花的浅红印。",
      reveal: "雾面显签：签纸先倒映在水面，再从雾里浮到船沿，文字像被慢水一点点送上岸。",
      ambientMotion: "浓雾缓慢漂移，水面几乎无波，远处尖石上的苔光闪一下，河里有古代鱼影掠过。",
      sound: "极轻船桨拨水、摆渡钱碰木盒、远处死神歌声的残响；整体安静到近乎没有风。",
      assetPrompt:
        "明亮日式二次元游戏资产，三途河抽签仪式道具：无帆朴素渡船边的小木签盒、旧船桨、几枚摆渡钱、灰蓝河雾短签纸、彼岸花浅红印、平静水面和少量雾气。干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：三途河分割此岸与彼岸，亡者乘坐死神的船渡河，小野塚小町是常见摆渡人。",
      "THBWiki：三途河水流极慢、几乎无声、永远无风，河上有浓雾、发光雾点和长苔尖石。",
      "THBWiki：渡船朴素无帆，全靠死神手摇船桨；摆渡钱会影响三途河宽度。",
    ],
    visual: {
      ink: "#f5fbff",
      accent: "#4f9bc4",
      secondary: "#dd6b76",
      shadow: "rgba(32, 77, 101, 0.34)",
      surface: "rgba(229, 246, 255, 0.76)",
      glow: "rgba(98, 174, 207, 0.34)",
      particle: "rgba(238, 250, 255, 0.74)",
    },
  },
  {
    id: "misty-lake",
    label: "雾之湖",
    subtitle: "湖雾在水纹上慢慢散开",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/misty-lake-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "misty-lake"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/misty-lake-ritual-kit-v1.webp",
    description: "雾从湖面贴着水纹散开，薄冰在托盘边缘轻轻响。偶尔有妖精光点从冷雾里飞过，把短签照得清清亮亮。",
    cardDescription: "湖雾推开水纹，半透明短签像薄冰一样浮出。",
    cornerLabel: "湖畔冰雾签",
    animationPlan: "冰雾水纹签",
    ritualPlan: {
      tool: "湖雾冰晶签盘：浅木托盘浮在湖边石上，托盘边缘结着薄冰，旁边有一颗妖精光点。",
      paper: "冰雾短签：浅蓝半透明短签纸，纸背有水纹和小冰晶压印。",
      reveal: "水纹推签：湖雾先盖住托盘，水纹从中心扩开，签纸像薄冰一样浮出并逐渐变清楚。",
      ambientMotion: "湖面雾气横向流动，落叶轻漂，偶尔有小冰晶从画面边缘飞过，远处红馆轮廓只留一点影。",
      sound: "清水轻拍湖岸、冰晶细碎声、妖精光点掠过的轻响，清爽但略冷。",
      assetPrompt:
        "明亮日式二次元游戏资产，雾之湖抽签仪式道具：湖边石上的浅木托盘、薄冰边缘、浅蓝半透明短签纸、水纹、少量冰晶、一个小妖精光点和低雾。干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：雾之湖位于妖怪之山山脚，白天被浓雾覆盖，视界差且寒冷。",
      "THBWiki：雾之湖湖水清澈、湖上有雾气，湖畔有琪露诺、大妖精活动，若鹭姬居住在湖中。",
      "THBWiki：红魔馆位于雾之湖附近，后续画面可远景暗示但不应抢走湖雾主题。",
    ],
    visual: {
      ink: "#f1fbff",
      accent: "#60b9df",
      secondary: "#a6d9ff",
      shadow: "rgba(43, 104, 130, 0.28)",
      surface: "rgba(229, 248, 255, 0.78)",
      glow: "rgba(112, 200, 232, 0.34)",
      particle: "rgba(240, 252, 255, 0.78)",
    },
  },
  {
    id: "human-village",
    label: "人间之里",
    subtitle: "店招与布告把日常签意照亮",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/human-village-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "human-village"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/human-village-ritual-kit-v1.webp",
    description: "店招在巷口轻轻晃着，布告纸角被晚风掀起。人间之里的签藏在小木抽屉里，带一点账册墨味，也带一点刚有人走过的热闹。",
    cardDescription: "灯笼照着纸签抽屉，街风把日常签翻到正面。",
    cornerLabel: "街巷日常签",
    animationPlan: "街灯纸签",
    ritualPlan: {
      tool: "街巷纸签抽屉：低矮店铺门口的小木抽屉，旁边放账册、旧布告和一盏暖色灯笼。",
      paper: "日常街签：米白短签纸，边角像被店铺账册压过，盖有淡淡店印与小路纹。",
      reveal: "抽屉滑开揭签：灯笼先轻晃，纸签从木抽屉里露出半截，再被街风翻到正面。",
      ambientMotion: "布告纸角轻动、远处门帘掀起、巷口有一瞬刚离开的影子，整体保持人类村落的生活感。",
      sound: "木抽屉滑动、店招轻响、远处脚步和低声寒暄，声音亲近、日常，不做神社铃声。",
      assetPrompt:
        "明亮日式二次元游戏资产，人间之里日常街巷抽签仪式道具：低矮店铺门口的小木纸签抽屉、暖色灯笼、旧布告、店招、账册、米白短签纸和街风纸角，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：人类村落是幻想乡人类主要居住地，包含街道、商铺、民居、村口、农田和小道等日常空间。",
      "THBWiki：人类村落相关场景可延伸到铃奈庵、鲵吞亭、寺子屋等人类生活据点。",
      "v2 背景强化了店招、布告和有人刚离开的街巷感，定位为日常街巷签而非观光街景。",
    ],
    visual: {
      ink: "#fff8ef",
      accent: "#d58a54",
      secondary: "#75b7b1",
      shadow: "rgba(132, 78, 44, 0.3)",
      surface: "rgba(255, 242, 224, 0.78)",
      glow: "rgba(225, 146, 86, 0.34)",
      particle: "rgba(255, 248, 235, 0.76)",
    },
  },
  {
    id: "sunflower-field",
    label: "向日葵田",
    subtitle: "花海里的影子比阳光慢半拍",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/sunflower-field-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "sunflower-field"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/sunflower-field-ritual-kit-v1.webp",
    description: "向日葵把脸转向阳光，地上的影子却慢了半拍。旧木牌旁的小签箱自己开了一线，花瓣把金色短签送出来。",
    cardDescription: "阳伞投下错位花影，淡金短签随花瓣升起。",
    cornerLabel: "花田异变签",
    animationPlan: "花影季节签",
    ritualPlan: {
      tool: "花田签箱与阳伞：旧木牌下的小签箱，箱盖被阳光晒亮，旁边立一把偏旧的花田阳伞。",
      paper: "金色季节签：淡金短签纸，纸背压有向日葵花盘纹和很浅的伞影。",
      reveal: "花影偏移揭签：风吹花海时签箱打开，签纸随花瓣升起，地面影子慢半拍后才对齐。",
      ambientMotion: "向日葵轻摆、花瓣从前景掠过、旧木牌投下略微不合常理的影子，阳光明亮但保留异变感。",
      sound: "夏风穿过花盘、木牌轻响、纸签被风掀起的细声，远处可以有很轻的伞柄碰木箱声。",
      assetPrompt:
        "明亮日式二次元游戏资产，向日葵田季节异变抽签仪式道具：旧木牌、小签箱、偏旧阳伞、淡金短签纸、向日葵花瓣、轻微错位的影子，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：太阳花田是幻想乡深处的向日葵花田，是花之异变相关舞台意象之一。",
      "THBWiki / Touhou Wiki：风见幽香与花、花朵操纵和太阳花田意象高度相关，可转化为阳伞、花盘、花影和季节异变感。",
      "v2 背景已加入旧木牌、伞、签箱和轻微异变影子，定位为季节异变签而非普通花田宣传图。",
    ],
    visual: {
      ink: "#fffbea",
      accent: "#d9a928",
      secondary: "#7dbf75",
      shadow: "rgba(132, 99, 26, 0.28)",
      surface: "rgba(255, 248, 215, 0.78)",
      glow: "rgba(230, 188, 70, 0.34)",
      particle: "rgba(255, 252, 221, 0.78)",
    },
  },
  {
    id: "divine-spirit-mausoleum",
    label: "神灵庙",
    subtitle: "仙界道场的琉璃瓦下，灵光沿方砖归位",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/divine-spirit-mausoleum-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "divine-spirit-mausoleum"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/divine-spirit-mausoleum-ritual-kit-v1.webp",
    description: "仙界的石阶把脚步声收得很轻，红柱和琉璃瓦在灵光里发亮。铜铃一响，道符沿方砖归位，青白灵签从供案上竖起。",
    cardDescription: "铜铃唤起道符光阵，青白灵签在八角影中点亮。",
    cornerLabel: "仙界灵签",
    animationPlan: "道符灵光签",
    ritualPlan: {
      tool: "参庙签台：简洁供案配玉笏、铜铃和几张无字道教符，重点让石阶与八角塔说话。",
      paper: "仙界灵签：青白符纸配少量金色边线，纸面只保留简洁云纹和几颗灵光。",
      reveal: "符光归位：道符沿方砖广场排成简单八角形，铜铃一响，灵签从供案上竖起并逐段点亮签意。",
      ambientMotion: "屋檐金光轻闪、灯笼慢摆、少量青绿色神灵粒子沿石阶上升，整体保持干净留白。",
      sound: "细铜铃、香火轻响、石阶回音和极轻的道教法器声，整体明亮、庄严、带一点仙界错位感。",
      assetPrompt:
        "干净日式二次元游戏背景，风格与现有 generated-themes 场景保持一致：神灵庙仙界道场、直向石阶、简洁方砖广场、上翘檐、红柱、金色屋檐、两座八角侧塔、少量青绿色神灵粒子，前景只放简单供案、铜铃和几张无字道教符。少道具、少纹理、低复杂度、可放 UI 文案。无角色，无文字，不要普通神社鸟居，不要泛用森林神庙，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：神灵庙是丰聪耳神子在仙界中的道场，物部布都、苏我屠自古、霍青娥等也在此居住。",
      "THBWiki：神灵庙具有三层上翘房檐、龙凤瑞兽、彩绘红柱、金色琉璃瓦、两侧八角塔和方砖广场。",
      "THBWiki：梦殿大祀庙入口形似道观大门，并有道教神仙绘画；神灵庙相关图要优先强化道教庙观与仙界感。",
    ],
    visual: {
      ink: "#f7fff5",
      accent: "#49a987",
      secondary: "#d4b853",
      shadow: "rgba(33, 82, 73, 0.32)",
      surface: "rgba(224, 250, 238, 0.78)",
      glow: "rgba(89, 204, 164, 0.34)",
      particle: "rgba(238, 255, 244, 0.8)",
    },
  },
  {
    id: "nameless-hill",
    label: "无名之丘",
    subtitle: "荒野风声把铃兰影子吹远",
    status: "locked",
    sceneImage: "/images/optimized/generated-themes/expanded/nameless-hill-scene-v2.webp",
    ritualAssets: buildRitualAssets("expanded", "nameless-hill"),
    ritualImage: "/images/optimized/generated-themes/expanded/rituals/nameless-hill-ritual-kit-v1.webp",
    description: "山丘上几乎没有风，铃兰的影子贴着薄雾。没有标签的小玻璃瓶半埋在草间，签纸慢慢滑出，像终于想起自己的名字。",
    cardDescription: "静雾从无名签瓶里升起，灰白短签最后显出字迹。",
    cornerLabel: "铃兰无名签",
    animationPlan: "静雾铃兰签",
    ritualPlan: {
      tool: "铃兰无名签瓶：一只没有标签的小玻璃瓶半埋在山丘草间，瓶口系着褪色细绳。",
      paper: "无名铃兰签：灰白短签纸，纸角有淡绿色铃兰影，留出一块像被擦掉名字的空白。",
      reveal: "静雾开瓶：没有风，瓶中薄雾自行升起，签纸缓慢滑出，空白处最后才显出签意。",
      ambientMotion: "铃兰几乎不摆动，冷雾贴地，远处山坡光线很低，偶尔有幽灵般的小光点经过。",
      sound: "近乎无声，只保留玻璃轻碰、草叶细响和低低耳鸣感，突出无风与被遗忘的气氛。",
      assetPrompt:
        "明亮但克制的日式二次元游戏资产，无名之丘抽签仪式道具：阴冷山丘草间的小玻璃瓶、褪色细绳、灰白短签纸、淡绿色铃兰影、贴地薄雾和少量幽灵光点。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：无名之丘位于妖怪之山对面，山丘中腹有大量铃兰田，日照不强、气温偏低且有毒气息。",
      "THBWiki：梅蒂欣·梅兰可莉诞生并居住于无名之丘，她是被丢弃在铃兰田里的人偶化作的妖怪。",
      "THBWiki：无名之丘有被遗忘和无风的设定，仪式应避免普通荒野风声，改用静雾、玻璃瓶与铃兰毒意。",
    ],
    visual: {
      ink: "#f9f7ef",
      accent: "#8d9870",
      secondary: "#c8b78a",
      shadow: "rgba(77, 86, 60, 0.28)",
      surface: "rgba(243, 240, 224, 0.78)",
      glow: "rgba(151, 164, 118, 0.3)",
      particle: "rgba(251, 249, 239, 0.74)",
    },
  },
];

function getRouteTextTone(sceneId: OmamoriRouteId): OmamoriRouteConfig["textTone"] {
  if (sceneId === "scarlet" || sceneId === "palace-of-earth-spirits") {
    return "mansion";
  }

  if (
    sceneId === "eientei" ||
    sceneId === "hakugyokurou" ||
    sceneId === "sanzu-river" ||
    sceneId === "misty-lake" ||
    sceneId === "nameless-hill"
  ) {
    return "moon";
  }

  return "shrine";
}

const EXPANDED_ROUTE_ACTION_COPY: Record<
  Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>,
  Pick<
    OmamoriRouteConfig,
    "enterLabel" | "drawLabel" | "revisitLabel" | "statusIdle" | "resultTitle"
  >
> = {
  "moriya-shrine": {
    enterLabel: "登上守矢参道",
    drawLabel: "摇响风祝卷轴签",
    revisitLabel: "重展山风神签",
    statusIdle: "今日尚未登山参拜",
    resultTitle: "守矢风祝签",
  },
  hakugyokurou: {
    enterLabel: "踏入白玉樱庭",
    drawLabel: "启开幽冥冥签",
    revisitLabel: "重读樱庭冥签",
    statusIdle: "今日尚未入庭启签",
    resultTitle: "白玉楼冥签",
  },
  "forest-of-magic": {
    enterLabel: "走近林中书页",
    drawLabel: "翻动星屑纸符",
    revisitLabel: "重看魔导纸符",
    statusIdle: "今日尚未翻开魔导书",
    resultTitle: "魔法森林纸符",
  },
  "myouren-temple": {
    enterLabel: "沿寺灯入廊",
    drawLabel: "展开莲纹经卷签",
    revisitLabel: "重展莲灯寺签",
    statusIdle: "今日尚未在寺灯下问签",
    resultTitle: "命莲寺莲灯签",
  },
  "palace-of-earth-spirits": {
    enterLabel: "进入地底回廊",
    drawLabel: "开启心读余火签",
    revisitLabel: "重看地底心签",
    statusIdle: "今日尚未让签匣读心",
    resultTitle: "地灵殿心签",
  },
  "sanzu-river": {
    enterLabel: "靠近三途渡船",
    drawLabel: "拨开河雾渡签",
    revisitLabel: "重读渡河雾签",
    statusIdle: "今日尚未付下摆渡钱",
    resultTitle: "三途川渡签",
  },
  "misty-lake": {
    enterLabel: "停在湖雾岸边",
    drawLabel: "推开冰雾短签",
    revisitLabel: "重看湖畔冰签",
    statusIdle: "今日尚未让薄冰响起",
    resultTitle: "雾之湖冰雾签",
  },
  "human-village": {
    enterLabel: "走进人间街巷",
    drawLabel: "拉开灯下纸签屉",
    revisitLabel: "重读街巷便签",
    statusIdle: "今日尚未开屉问签",
    resultTitle: "人间之里街签",
  },
  "sunflower-field": {
    enterLabel: "穿过向日葵影",
    drawLabel: "启开花田季节签",
    revisitLabel: "重看花影金签",
    statusIdle: "今日尚未听花影偏移",
    resultTitle: "向日葵田季节签",
  },
  "divine-spirit-mausoleum": {
    enterLabel: "登上神灵石阶",
    drawLabel: "点亮道符灵签",
    revisitLabel: "重展仙界灵签",
    statusIdle: "今日尚未敲响灵庙铜铃",
    resultTitle: "神灵庙道符签",
  },
  "nameless-hill": {
    enterLabel: "走向铃兰薄雾",
    drawLabel: "开启无名签瓶",
    revisitLabel: "重读铃兰无名签",
    statusIdle: "今日尚未打开无名瓶口",
    resultTitle: "无名之丘瓶签",
  },
};

const EXPANDED_ROUTE_COPY_LABELS: Record<Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>, OmamoriRouteConfig["copyLabels"]> = {
  "moriya-shrine": {
    heading: "山上风祝签",
    quote: "注连所示",
    summary: "卷轴签意",
    advice: "风祝一札",
    luckyColor: "今日风色",
    luckyItem: "随身纸垂",
    motif: "注连纹样",
    rare: "奇迹粒子",
    channel: "山风签路",
    inspiration: "御柱旁注",
  },
  hakugyokurou: {
    heading: "幽冥樱签",
    quote: "刀光所示",
    summary: "冥签签意",
    advice: "樱庭短笺",
    luckyColor: "今日樱色",
    luckyItem: "随身花瓣",
    motif: "冥樱纹样",
    rare: "冷光回响",
    channel: "樱庭签路",
    inspiration: "石阶记事",
  },
  "forest-of-magic": {
    heading: "森林魔导签",
    quote: "书页所示",
    summary: "纸符签意",
    advice: "林中批注",
    luckyColor: "今日星屑",
    luckyItem: "随身玻璃瓶",
    motif: "蘑菇星纹",
    rare: "孢子闪光",
    channel: "魔导签路",
    inspiration: "玻璃瓶标签",
  },
  "myouren-temple": {
    heading: "莲灯寺签",
    quote: "灯下所示",
    summary: "莲纹签意",
    advice: "寺廊短偈",
    luckyColor: "今日灯色",
    luckyItem: "随身莲纹",
    motif: "莲花纹样",
    rare: "夜法会回声",
    channel: "寺灯签路",
    inspiration: "木鱼旁注",
  },
  "palace-of-earth-spirits": {
    heading: "地底心签",
    quote: "余火所示",
    summary: "心读签意",
    advice: "地砖低语",
    luckyColor: "今日余火",
    luckyItem: "随身小钥",
    motif: "第三眼纹",
    rare: "第三眼闪烁",
    channel: "旧地狱签路",
    inspiration: "方砖热痕",
  },
  "sanzu-river": {
    heading: "渡河雾签",
    quote: "船沿所示",
    summary: "河雾签意",
    advice: "摆渡短语",
    luckyColor: "今日河雾",
    luckyItem: "随身渡钱",
    motif: "彼岸花纹",
    rare: "渡钱异响",
    channel: "渡河签路",
    inspiration: "船桨水痕",
  },
  "misty-lake": {
    heading: "湖畔冰雾签",
    quote: "薄冰所示",
    summary: "冰雾签意",
    advice: "湖畔短句",
    luckyColor: "今日冰蓝",
    luckyItem: "随身冰晶",
    motif: "湖雾纹样",
    rare: "妖精光点",
    channel: "冰雾签路",
    inspiration: "水纹边注",
  },
  "human-village": {
    heading: "街巷日常签",
    quote: "抽屉所示",
    summary: "街签签意",
    advice: "里巷便条",
    luckyColor: "今日灯笼色",
    luckyItem: "随身店印",
    motif: "街巷纹样",
    rare: "店招异响",
    channel: "里巷签路",
    inspiration: "账册纸角",
  },
  "sunflower-field": {
    heading: "花田异变签",
    quote: "伞影所示",
    summary: "季节签意",
    advice: "花盘耳语",
    luckyColor: "今日葵金",
    luckyItem: "随身花瓣",
    motif: "花盘纹样",
    rare: "慢拍影子",
    channel: "花影签路",
    inspiration: "阳伞投影",
  },
  "divine-spirit-mausoleum": {
    heading: "仙界灵签",
    quote: "铜铃所示",
    summary: "道符签意",
    advice: "灵庙符语",
    luckyColor: "今日青白",
    luckyItem: "随身铜铃",
    motif: "八角光阵",
    rare: "八角阵光",
    channel: "仙界签路",
    inspiration: "石阶灵光",
  },
  "nameless-hill": {
    heading: "铃兰无名签",
    quote: "瓶中所示",
    summary: "无名签意",
    advice: "铃兰低声",
    luckyColor: "今日雾白",
    luckyItem: "随身细绳",
    motif: "铃兰影纹",
    rare: "空白显名",
    channel: "无名签路",
    inspiration: "褪色细绳",
  },
};

const EXPANDED_ROUTE_STAGE_COPY: Record<
  Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>,
  OmamoriRouteConfig["stage"]
> = {
  "moriya-shrine": {
    eyebrow: "山上参拜",
    title: "纸垂摆过山风，卷轴签从注连绳下垂落",
    description: "轻触风祝铃，等山风先把纸垂吹到同一边。守矢神社会把今日的奇迹压进淡绿卷轴里。",
    ringing: "风祝铃正把山风招到注连绳下",
    shaking: "卷轴签架被叶影托起，纸垂正在重排签意",
    revealing: "淡绿神签顺着山风向两侧展开",
    rareNotice: "奇迹粒子已沿注连绳亮起",
    favoriteAdded: "已收进本地山风签册",
    favoriteRemoved: "已把这张风祝签放回守矢参道",
  },
  hakugyokurou: {
    eyebrow: "樱庭启签",
    title: "刀光扫过樱庭，半透明冥签才肯显字",
    description: "轻触庭铃，让石阶薄雾慢一拍。白玉楼的签不会急着醒来，只在樱瓣落尽前露出该记住的一句。",
    ringing: "樱庭铃声正贴着石阶回廊走远",
    shaking: "半透明冥签被花雾托起，冷光掠过纸边",
    revealing: "樱瓣盖住又让开，冥签正缓缓显字",
    rareNotice: "冷光回响已在花下出现",
    favoriteAdded: "已收进本地樱签册",
    favoriteRemoved: "已把这张冥签放回白玉楼石阶",
  },
  "forest-of-magic": {
    eyebrow: "林中翻书",
    title: "旧魔导书翻错一页，星屑纸符从页缝浮起",
    description: "轻触书脊，先别惊动那些会发光的蘑菇。森林会把潮气、星粉和一点失败记录混在一起，再写出答案。",
    ringing: "玻璃瓶细响，蘑菇灯亮了一下",
    shaking: "旧魔导书自己翻页，星粉正沿纸边试写",
    revealing: "淡紫纸符从页缝升起，签意被孢子光点亮",
    rareNotice: "孢子闪光已从书页边缘冒出",
    favoriteAdded: "已收进本地魔导签册",
    favoriteRemoved: "已把这张纸符放回树根书页",
  },
  "myouren-temple": {
    eyebrow: "寺灯问签",
    title: "寺灯先亮，经卷才把莲纹短签推到木鱼旁",
    description: "轻触签台边的木鱼，听纸面从卷轴里慢慢醒来。命莲寺给出的提醒不急，却会稳稳落在灯下。",
    ringing: "寺灯铃声沿参拜道一盏盏亮起",
    shaking: "莲纹经卷正在木鱼轻响里摊平",
    revealing: "暖白短签从卷轴内侧滑出，停在寺灯边",
    rareNotice: "夜法会回声已在廊下出现",
    favoriteAdded: "已收进本地莲灯签册",
    favoriteRemoved: "已把这张寺签放回命莲寺灯下",
  },
  "palace-of-earth-spirits": {
    eyebrow: "地底读心",
    title: "第三只眼轻轻闭合，没说出口的话从余火里透出",
    description: "轻触心读签匣，先别急着移开视线。地灵殿会把藏在心底的念头像地热一样托上来。",
    ringing: "地热低鸣贴着方砖传来",
    shaking: "素黑签匣正在听取今日心音，透光砖忽明忽暗",
    revealing: "暗红紫心签从余火里显影",
    rareNotice: "第三眼闪烁已出现",
    favoriteAdded: "已收进本地地底签册",
    favoriteRemoved: "已把这张心签放回旧地狱余火",
  },
  "sanzu-river": {
    eyebrow: "河雾渡签",
    title: "摆渡钱碰响木盒，灰蓝短签从水影里靠岸",
    description: "轻触船沿的小木盒，等河雾自己让出一条窄路。三途川的签不催行程，只问你愿意带走哪一句。",
    ringing: "摆渡钱正轻碰渡船签盒",
    shaking: "船桨拨开雾面，短签倒影正在重排",
    revealing: "灰蓝雾签从水面靠岸，彼岸花印慢慢浮出",
    rareNotice: "渡钱异响已在船沿出现",
    favoriteAdded: "已收进本地渡河签册",
    favoriteRemoved: "已把这张雾签放回三途川船沿",
  },
  "misty-lake": {
    eyebrow: "湖畔启签",
    title: "薄冰先响一声，半透明短签才从水纹里浮出",
    description: "轻触湖边浅木托盘，让薄冰轻轻裂出一圈水纹。雾之湖会把今日提醒冻得清亮，再交到你手里。",
    ringing: "冰晶细声掠过湖面，妖精光点闪了一下",
    shaking: "水纹在浅木托盘里扩开，湖雾正在重排签意",
    revealing: "浅蓝短签像薄冰一样变得清楚",
    rareNotice: "妖精光点已停在签纸边",
    favoriteAdded: "已收进本地湖雾签册",
    favoriteRemoved: "已把这张短签放回雾之湖水纹",
  },
  "human-village": {
    eyebrow: "街巷问签",
    title: "木抽屉滑开半寸，灯笼把米白短签照亮",
    description: "轻触店门口的小抽屉，等布告纸角安静下来。人间之里的签像路过时听见的叮嘱，朴素，但有用。",
    ringing: "店招轻响从巷口传来",
    shaking: "纸签抽屉在账册旁翻找今日签意",
    revealing: "米白街签被晚风翻到正面",
    rareNotice: "店招异响已在灯下出现",
    favoriteAdded: "已收进本地街巷签册",
    favoriteRemoved: "已把这张街签放回人间之里抽屉",
  },
  "sunflower-field": {
    eyebrow: "花田听风",
    title: "阳伞影子慢半拍，淡金短签跟着花瓣升起",
    description: "轻触旧木牌下的小签箱，先别急着判断影子的方向。向日葵田会把答案晒得很亮，也留一点异变余味。",
    ringing: "夏风穿过花盘，旧木牌轻轻作响",
    shaking: "小签箱在伞影里打开一线，影子正在慢慢对齐",
    revealing: "淡金季节签随花瓣升起",
    rareNotice: "慢拍影子已落在纸背",
    favoriteAdded: "已收进本地花影签册",
    favoriteRemoved: "已把这张花田签放回旧木牌下",
  },
  "divine-spirit-mausoleum": {
    eyebrow: "仙界参庙",
    title: "铜铃一响，道符沿方砖归成八角光阵",
    description: "轻触供案前的铜铃，让石阶回音停在檐下。神灵庙的签意会从青白灵光里竖起，像一句端正的诏令。",
    ringing: "灵庙铜铃沿石阶回响，香火轻轻一亮",
    shaking: "道符正沿方砖归位，八角光阵重新排齐",
    revealing: "青白灵签从供案上立起并逐段点亮",
    rareNotice: "八角阵光已在檐下出现",
    favoriteAdded: "已收进本地灵庙签册",
    favoriteRemoved: "已把这张灵签放回神灵庙供案",
  },
  "nameless-hill": {
    eyebrow: "静雾启瓶",
    title: "没有风，灰白短签仍从无标签玻璃瓶里滑出",
    description: "轻触半埋在草间的小玻璃瓶。无名之丘的签来得很慢，像一件被忘记太久的事，终于愿意开口。",
    ringing: "玻璃轻碰声几乎被贴地薄雾吞没",
    shaking: "无名签瓶正在静雾里回收旧事",
    revealing: "灰白短签慢慢显名，铃兰影贴在纸角",
    rareNotice: "空白显名已在瓶口出现",
    favoriteAdded: "已收进本地无名签册",
    favoriteRemoved: "已把这张无名签放回铃兰薄雾",
  },
};

function createExpandedRouteConfig(scene: SceneCandidate): OmamoriRouteConfig {
  const sceneId = scene.id as OmamoriRouteId;
  const ritualAssets = scene.ritualAssets ?? buildRitualAssets("expanded", scene.id);
  const expandedSceneId = sceneId as Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>;
  const actionCopy = EXPANDED_ROUTE_ACTION_COPY[expandedSceneId];

  return {
    id: sceneId,
    label: scene.label,
    shortLabel: scene.label,
    subtitle: scene.subtitle,
    description: scene.description,
    cardDescription: scene.cardDescription,
    cornerLabel: scene.cornerLabel,
    enterLabel: actionCopy.enterLabel,
    drawLabel: actionCopy.drawLabel,
    revisitLabel: actionCopy.revisitLabel,
    backLabel: "重新选择入口",
    statusIdle: actionCopy.statusIdle,
    resultTitle: actionCopy.resultTitle,
    shareFrom: scene.label,
    sceneImage: scene.sceneImage,
    ritualImage: scene.ritualImage,
    textureImage: "/images/textures/washi-noise.svg",
    ritualAssets,
    textTone: getRouteTextTone(sceneId),
    copyTone: sceneId,
    ritualProfile: ROUTE_RITUAL_PROFILES[sceneId],
    visual: scene.visual,
    copyLabels: EXPANDED_ROUTE_COPY_LABELS[expandedSceneId],
    stage: EXPANDED_ROUTE_STAGE_COPY[expandedSceneId],
  };
}

const EXPANDED_OMAMORI_ROUTES = Object.fromEntries(
  SCENE_BLUEPRINTS
    .filter((scene) => !scene.routeId)
    .map((scene) => [scene.id, createExpandedRouteConfig(scene)]),
) as Record<Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>, OmamoriRouteConfig>;

export const OMAMORI_ROUTES = {
  ...BASE_OMAMORI_ROUTES,
  ...EXPANDED_OMAMORI_ROUTES,
} satisfies Record<OmamoriRouteId, OmamoriRouteConfig>;

export const OMAMORI_ROUTE_LIST = OMAMORI_ROUTE_IDS.map((routeId) => OMAMORI_ROUTES[routeId]);

export const SCENE_CANDIDATES: SceneCandidate[] = SCENE_BLUEPRINTS.map((scene) => {
  const routeId = (scene.routeId ?? scene.id) as OmamoriRouteId;
  const route = OMAMORI_ROUTES[routeId];

  return {
    ...scene,
    status: "active",
    routeId,
    cornerLabel: route.cornerLabel,
    ritualAssets: route.ritualAssets,
    visual: route.visual,
  };
});

export function isOmamoriRouteId(value: unknown): value is OmamoriRouteId {
  return typeof value === "string" && OMAMORI_ROUTE_IDS.includes(value as OmamoriRouteId);
}

export function getOmamoriRoute(routeId: OmamoriRouteId | undefined | null): OmamoriRouteConfig {
  return routeId && OMAMORI_ROUTES[routeId] ? OMAMORI_ROUTES[routeId] : OMAMORI_ROUTES.hakurei;
}

export const DRAW_TIMINGS = {
  closed: 780,
  shaking: 1320,
  emerging: 2600,
  open: 0,
  flash: 800,
  reducedBell: 220,
  reducedTube: 280,
  reducedEmerging: 360,
  reducedOpen: 0,
  reducedFlash: 220,
} as const;
