import type {
  FortuneCategory,
  FortuneRarity,
  FortuneTier,
  OmamoriRouteConfig,
  OmamoriRouteId,
  OmamoriSettings,
  RitualAssetSet,
  SceneCandidate,
} from "@/types/omikuji";

export const CATEGORY_LABELS: Record<FortuneCategory, string> = {
  study: "学习运",
  love: "感情运",
  slacking: "摸鱼运",
  lateNight: "熬夜运",
  social: "社恐出门运",
  wealth: "财富运",
  hidden: "隐藏稀有签",
};

export const TIER_LABELS: Record<FortuneTier, string> = {
  "small-blessing": "小吉",
  "middle-blessing": "中吉",
  "great-blessing": "大吉",
  shadow: "夜相",
  secret: "秘签",
};

export const RARITY_LABELS: Record<FortuneRarity, string> = {
  common: "常驻",
  uncommon: "微稀有",
  rare: "稀有",
  epic: "高稀有",
  legendary: "传说",
};

export const FORTUNE_RARITY_WEIGHTS: Record<FortuneRarity, number> = {
  common: 58,
  uncommon: 24,
  rare: 10,
  epic: 5,
  legendary: 2,
};

export const CATEGORY_DRAW_MODIFIER: Record<FortuneCategory, number> = {
  study: 1,
  love: 1,
  slacking: 0.94,
  lateNight: 0.9,
  social: 0.95,
  wealth: 0.75,
  hidden: 0.18,
};

export const DEFAULT_SETTINGS: OmamoriSettings = {
  ambienceEnabled: true,
  sfxEnabled: true,
  ambienceVolume: 0.4,
  sfxVolume: 0.7,
  reduceMotion: false,
  defaultRouteId: "hakurei",
  askRouteOnLaunch: true,
};

export const OMAMORI_ROUTE_IDS: OmamoriRouteId[] = [
  "hakurei",
  "scarlet",
  "eientei",
  "moriya-shrine",
  "hakugyokurou",
  "forest-of-magic",
  "myouren-temple",
  "palace-of-earth-spirits",
  "sanzu-river",
  "misty-lake",
  "human-village",
  "sunflower-field",
  "divine-spirit-mausoleum",
  "nameless-hill",
];

function buildRitualAssets(bucket: "active" | "expanded", sceneId: string): RitualAssetSet {
  const base = `/images/generated-themes/${bucket}/rituals/${sceneId}`;

  return {
    ritualBase: `${base}/ritual-base.png`,
    paperClosed: `${base}/paper-closed.png`,
    paperEmerging: `${base}/paper-emerging.png`,
    paperOpen: `${base}/paper-open.png`,
    fxParticles: `${base}/fx-particles.png`,
    fxReveal: `${base}/fx-reveal.png`,
    resultCorner: `${base}/result-corner.png`,
    sourceSheet: `${base}/source-sheet-v1.png`,
  };
}

const BASE_OMAMORI_ROUTES = {
  hakurei: {
    id: "hakurei",
    label: "博丽神社",
    shortLabel: "神社",
    subtitle: "先在结界边缘停一停",
    description:
      "朱红鸟居与旧白墙把夜色压低。铃声穿过结界，今日的签纸会从旧木匣里醒来。",
    cardDescription: "铃声穿过结界，今日的签纸会从旧木匣里醒来。",
    cornerLabel: "正统神社签",
    enterLabel: "前往神社参拜",
    drawLabel: "抽取今日签文",
    revisitLabel: "展开今日签文",
    backLabel: "重新选择入口",
    statusIdle: "今日尚未参拜",
    resultTitle: "今日签文",
    shareFrom: "博丽神社",
    sceneImage: "/images/generated-themes/active/hakurei-scene.png",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/ofuda-field.svg",
    stageOverlayImage: "/images/generated-themes/active/hakurei-stage-props.svg",
    ritualImage: "/images/generated-themes/active/rituals/hakurei-ritual-kit-v1.png",
    ritualAssets: buildRitualAssets("active", "hakurei"),
    textTone: "shrine",
    visual: {
      ink: "#f8efe7",
      accent: "#d94b4b",
      secondary: "#d8b15f",
      shadow: "rgba(89, 16, 22, 0.42)",
      surface: "rgba(42, 15, 18, 0.72)",
      glow: "rgba(217, 75, 75, 0.34)",
      particle: "rgba(248, 239, 231, 0.42)",
    },
    copyLabels: {
      heading: "今日签文",
      quote: "签中所示",
      summary: "签意",
      advice: "神社建议",
      luckyColor: "今日护色",
      luckyItem: "随身小物",
      motif: "签面纹样",
      rare: "异常回响",
      channel: "签文频道",
      inspiration: "灵感说明",
    },
    stage: {
      eyebrow: "今夜参拜",
      title: "铃响之后，今日签文会从纸尘里展开",
      description:
        "轻触铃绳，等结界的回声沉下来。铃音会在第一次点击后唤起，随后陪着签纸展开。",
      ringing: "神乐铃正在穿过结界",
      shaking: "旧木签筒正在重排今日签意",
      revealing: "签文正在展开",
      rareNotice: "异常回响已出现",
      favoriteAdded: "已收进本地签册",
      favoriteRemoved: "已把这张签文放回神社回声里",
    },
  },
  scarlet: {
    id: "scarlet",
    label: "红魔馆",
    shortLabel: "红魔馆",
    subtitle: "湖畔洋馆的茶会已经备好",
    description:
      "雾之湖的水光照亮红砖洋馆。玫瑰、蝙蝠剪影和红茶香气一起，把今日签意递到银托盘上。",
    cardDescription: "玫瑰与红茶香会把今日签意送到窗边。",
    cornerLabel: "洋馆茶会",
    enterLabel: "走向湖畔红馆",
    drawLabel: "开启红茶占签",
    revisitLabel: "重读茶会签笺",
    backLabel: "更换入口",
    statusIdle: "今日尚未赴约",
    resultTitle: "红馆茶会签",
    shareFrom: "红魔馆",
    sceneImage: "/images/generated-themes/active/scarlet-scene.png",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/scarlet-roses.svg",
    stageOverlayImage: "/images/generated-themes/active/scarlet-stage-props.svg",
    ritualImage: "/images/generated-themes/active/rituals/scarlet-ritual-kit-v1.png",
    ritualAssets: buildRitualAssets("active", "scarlet"),
    textTone: "mansion",
    visual: {
      ink: "#fff8f6",
      accent: "#e84f72",
      secondary: "#8fc5ff",
      shadow: "rgba(200, 64, 90, 0.2)",
      surface: "rgba(255, 238, 242, 0.78)",
      glow: "rgba(255, 128, 154, 0.34)",
      particle: "rgba(255, 237, 244, 0.72)",
    },
    copyLabels: {
      heading: "红馆茶会签",
      quote: "窗边絮语",
      summary: "茶会签意",
      advice: "洋馆建议",
      luckyColor: "今日茶色",
      luckyItem: "随身点心",
      motif: "玫瑰纹章",
      rare: "红雾回响",
      channel: "茶会频道",
      inspiration: "灵感说明",
    },
    stage: {
      eyebrow: "湖畔茶会",
      title: "银托盘轻响，今日签笺会从玫瑰旁展开",
      description:
        "轻触红茶铃，等湖风掀起窗纱。红魔馆的签笺会带着一点优雅和一点任性出现。",
      ringing: "红茶铃正在唤醒洋馆回廊",
      shaking: "银托盘正在重排今日茶会签意",
      revealing: "玫瑰签笺正在展开",
      rareNotice: "红雾回响已出现",
      favoriteAdded: "已收进本地茶会册",
      favoriteRemoved: "已把这张签笺放回红馆窗边",
    },
  },
  eientei: {
    id: "eientei",
    label: "永远亭",
    shortLabel: "永远亭",
    subtitle: "迷途竹林里，月光正落在纸门上",
    description:
      "竹叶筛下柔亮月色，白兔脚步在廊下轻轻跑过。药师的纸札与月都的微光，会把今日建议写得更清楚。",
    cardDescription: "竹叶、月光与纸门上的微光，会把今日建议收进一枚温柔签里。",
    cornerLabel: "月下药签",
    enterLabel: "走入迷途竹林",
    drawLabel: "抽取月下药签",
    revisitLabel: "展开月下药签",
    backLabel: "重选入口",
    statusIdle: "今日尚未问药",
    resultTitle: "永远亭月签",
    shareFrom: "永远亭",
    sceneImage: "/images/generated-themes/active/eientei-scene.png",
    textureImage: "/images/textures/washi-noise.svg",
    ornamentImage: "/images/generated-themes/active/eientei-bamboo.svg",
    stageOverlayImage: "/images/generated-themes/active/eientei-stage-props.svg",
    ritualImage: "/images/generated-themes/active/rituals/eientei-ritual-kit-v1.png",
    ritualAssets: buildRitualAssets("active", "eientei"),
    textTone: "moon",
    visual: {
      ink: "#f7fff7",
      accent: "#65b987",
      secondary: "#d6b8ff",
      shadow: "rgba(74, 143, 108, 0.2)",
      surface: "rgba(236, 255, 239, 0.78)",
      glow: "rgba(126, 204, 151, 0.3)",
      particle: "rgba(246, 255, 246, 0.78)",
    },
    copyLabels: {
      heading: "永远亭月签",
      quote: "月下处方",
      summary: "药签签意",
      advice: "竹林建议",
      luckyColor: "今日月色",
      luckyItem: "随身药包",
      motif: "竹叶纹样",
      rare: "月都回响",
      channel: "药签频道",
      inspiration: "灵感说明",
    },
    stage: {
      eyebrow: "竹林问药",
      title: "月兔跑过回廊，药签从竹影里亮起来",
      description:
        "轻触月铃，让竹叶的沙沙声慢下来。永远亭会给今天配一份温柔但不含糊的建议。",
      ringing: "月铃正在穿过迷途竹林",
      shaking: "药签匣正在配制今日签意",
      revealing: "月下药签正在展开",
      rareNotice: "月都回响已出现",
      favoriteAdded: "已收进本地月签册",
      favoriteRemoved: "已把这张药签放回竹林月色里",
    },
  },
} satisfies Record<"hakurei" | "scarlet" | "eientei", OmamoriRouteConfig>;

const BASE_OMAMORI_ROUTE_LIST = Object.values(BASE_OMAMORI_ROUTES);

const ACTIVE_SCENE_CANDIDATES: SceneCandidate[] = BASE_OMAMORI_ROUTE_LIST.map((route) => ({
  id: route.id,
  label: route.label,
  subtitle: route.subtitle,
  status: "active",
  sceneImage: route.sceneImage,
  ritualImage: `/images/generated-themes/active/rituals/${route.id}-ritual-kit-v1.png`,
  ritualAssets: route.ritualAssets,
  routeId: route.id,
  description: route.description,
  cardDescription: route.cardDescription,
  cornerLabel: route.cornerLabel,
  animationPlan: route.stage.title,
  visual: route.visual,
}));

const SCENE_BLUEPRINTS: SceneCandidate[] = [
  ...ACTIVE_SCENE_CANDIDATES,
  {
    id: "moriya-shrine",
    label: "守矢神社",
    subtitle: "山风从注连绳下穿过",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/moriya-shrine-scene.png",
    ritualAssets: buildRitualAssets("expanded", "moriya-shrine"),
    ritualImage: "/images/generated-themes/expanded/rituals/moriya-shrine-ritual-kit-v1.png",
    description: "风从妖怪之山的参道卷下来，纸垂在注连绳下轻轻打结。守矢的铃声比山脚更亮，签纸会带着一点奇迹的余温落到掌心。",
    cardDescription: "山风掠过注连绳，卷轴签在风祝铃声里展开。",
    cornerLabel: "山上风祝签",
    animationPlan: "山风卷轴签",
    ritualPlan: {
      tool: "风祝铃与注连绳签架：以山中神社的参拜铃为核心，铃柄带纸垂与御柱感木纹。",
      paper: "细长神签卷轴：淡绿和白色和纸，边缘有风纹、蛙纹与蛇形注连纹压印。",
      reveal: "山风卷开签轴：铃响后纸垂先摆动，卷轴被风托起，再从中心向两侧展开。",
      ambientMotion: "高空云影、纸垂摆动、叶片沿对角线掠过，偶尔出现奇迹粒子沿注连绳滑动。",
      sound: "清脆神乐铃、山风穿过树梢、远处祭典太鼓的低频点缀，整体比博丽神社更开阔。",
      assetPrompt:
        "明亮日式二次元游戏资产，一组守矢神社风祝抽签仪式道具：风祝铃、注连绳签架、淡绿白色神签卷轴、纸垂、山风叶片与奇迹粒子，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：守矢神社位于妖怪之山，是东方风神录相关场景。",
      "THBWiki / Touhou Wiki：东风谷早苗是守矢神社风祝，关联奇迹与神事语境。",
      "THBWiki / Touhou Wiki：八坂神奈子、洩矢诹访子与守矢神社信仰体系相关，可转化为注连绳、蛇/蛙纹样与山神氛围。",
    ],
    visual: {
      ink: "#f8fff4",
      accent: "#58a66d",
      secondary: "#b8d96a",
      shadow: "rgba(38, 92, 58, 0.34)",
      surface: "rgba(231, 250, 225, 0.74)",
      glow: "rgba(120, 202, 127, 0.34)",
      particle: "rgba(238, 255, 225, 0.72)",
    },
  },
  {
    id: "hakugyokurou",
    label: "白玉楼",
    subtitle: "樱庭尽头的冥界回廊",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/hakugyokurou-scene.png",
    ritualAssets: buildRitualAssets("expanded", "hakugyokurou"),
    ritualImage: "/images/generated-themes/expanded/rituals/hakugyokurou-ritual-kit-v1.png",
    description: "樱花落到石阶上，没有急着融进冥界的雾里。白玉楼的签纸很轻，像被庭师的刀光翻过一面，慢慢露出今日该记住的话。",
    cardDescription: "半透明冥签被樱瓣托起，冷色刀光扫过纸面。",
    cornerLabel: "幽冥樱签",
    animationPlan: "樱庭冥签",
    ritualPlan: {
      tool: "樱庭签台：带细雕栏板与石阶底座的白木签台，边缘挂薄樱花穗。",
      paper: "半透明冥签：薄樱粉与银白相间的和纸，纸面隐约透出庭院樱枝与月影。",
      reveal: "刀光映签：拔刀的冷光先扫过纸面，再由花瓣飘落遮住文字，最后缓慢显形。",
      ambientMotion: "樱花逆风旋转、薄雾沿石阶缓行、纸面有轻微发光波纹，整体安静但不死寂。",
      sound: "竹笛、远处风铃、剑鞘轻响和低沉回音，声音比守矢更柔，更空。",
      assetPrompt:
        "明亮日式二次元游戏资产，一组白玉楼幽冥抽签仪式道具：樱庭签台、半透明冥签、佩刀冷光、樱花花瓣、薄雾与石阶元素，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：白玉楼是与冥界、庭院、樱花意象相关的重要场景。",
      "THBWiki / Touhou Wiki：西行寺幽幽子与白玉楼、樱花庭院的意象高度绑定。",
      "THBWiki / Touhou Wiki：魂魄妖梦与刀、庭院守卫语境相关，可转化为刀光揭签的仪式方式。",
    ],
    visual: {
      ink: "#fff7fb",
      accent: "#e785b2",
      secondary: "#cbb8ff",
      shadow: "rgba(126, 61, 105, 0.3)",
      surface: "rgba(255, 238, 247, 0.76)",
      glow: "rgba(239, 145, 190, 0.34)",
      particle: "rgba(255, 243, 249, 0.78)",
    },
  },
  {
    id: "forest-of-magic",
    label: "魔法森林",
    subtitle: "星屑藏在蘑菇伞影里",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/forest-of-magic-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "forest-of-magic"),
    ritualImage: "/images/generated-themes/expanded/rituals/forest-of-magic-ritual-kit-v1.png",
    description: "树根旁的旧魔导书自己翻了一页，蘑菇灯在潮气里亮一下又暗下去。森林里的签文不太守规矩，星屑会先跑到纸边，再把答案推出来。",
    cardDescription: "魔导书翻到空白页，星屑纸符从页缝里浮起。",
    cornerLabel: "森林魔导签",
    animationPlan: "星屑纸符",
    ritualPlan: {
      tool: "蘑菇魔导书台：一本半开的旧魔法书压在树根上，旁边只有两三枚发光蘑菇和小玻璃瓶。",
      paper: "星屑纸符：淡紫短符纸，边缘有少量星粉和蘑菇孢子点，不做复杂符文墙。",
      reveal: "书页翻风揭签：魔法书自动翻到空白页，纸符从页缝里浮起，星屑沿纸边点亮签意。",
      ambientMotion: "孢子光点慢慢上浮，树影遮住又露出纸符，偶尔有一枚蘑菇像小灯一样亮一下。",
      sound: "纸页轻翻、玻璃瓶细响、低低的魔力嗡鸣和远处树叶声，整体阴湿但带一点好奇心。",
      assetPrompt:
        "明亮日式二次元游戏资产，魔法森林抽签仪式道具：树根上的半开旧魔法书、两三枚发光蘑菇、小玻璃瓶、淡紫星屑纸符、少量漂浮孢子光点。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：魔法森林是幻想乡中阴暗潮湿的原始森林，妖怪蘑菇孢子与瘴气使其不适合人类居住。",
      "THBWiki：魔法森林中住着雾雨魔理沙、爱丽丝等魔法使，蘑菇也与提升魔力的设定相关。",
      "THBWiki：森林内有香霖堂、废弃洋馆、信号塔等边缘物件，后续素材可保留少量旧物感但不要堆满杂物。",
    ],
    visual: {
      ink: "#f7f6ff",
      accent: "#8d78dc",
      secondary: "#f2c85e",
      shadow: "rgba(66, 50, 120, 0.32)",
      surface: "rgba(239, 235, 255, 0.76)",
      glow: "rgba(147, 126, 220, 0.34)",
      particle: "rgba(255, 247, 205, 0.72)",
    },
  },
  {
    id: "myouren-temple",
    label: "命莲寺",
    subtitle: "莲纹灯影沿着寺廊铺开",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/myouren-temple-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "myouren-temple"),
    ritualImage: "/images/generated-themes/expanded/rituals/myouren-temple-ritual-kit-v1.png",
    description: "寺灯沿着参拜道慢慢亮起，木鱼声落在夜风里。命莲寺的签不催人，它先把经卷摊平，再让莲纹从纸角浮出来。",
    cardDescription: "寺灯照着经卷签台，莲纹短签安静滑出。",
    cornerLabel: "莲灯寺签",
    animationPlan: "莲纹经卷签",
    ritualPlan: {
      tool: "莲纹经卷签台：青石参拜道旁的小经卷台，配一盏寺院灯和一只朴素木鱼。",
      paper: "莲纹寺签：暖白短签纸，边缘压莲纹，背面只留一条像经卷轴心的细线。",
      reveal: "经卷展开揭签：寺灯先亮，经卷慢慢展开，莲纹纸签从卷轴内侧滑出并停在木鱼旁。",
      ambientMotion: "石灯笼微光、樱花瓣少量落下、参拜道远处有夜间妖怪法会的模糊灯影。",
      sound: "木鱼轻敲、经卷纸面展开、石灯笼旁的夜风和远处低声诵读，稳重但不沉闷。",
      assetPrompt:
        "明亮日式二次元游戏资产，命莲寺抽签仪式道具：青石参拜道、小经卷台、暖色寺院灯、朴素木鱼、莲纹短签纸、少量樱花瓣。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：命莲寺由圣白莲建立，位于人类村落外，是以妖怪修行为重要语境的寺庙。",
      "THBWiki：命莲寺包含山门、正殿、钟楼、参拜道、石灯笼和墓地，正殿前有青色砖石参拜道。",
      "THBWiki：命莲寺白天安静庄严，夜晚因妖怪寄居和法会语境变得热闹，可转化为远处灯影和低声诵读。",
    ],
    visual: {
      ink: "#fffaf0",
      accent: "#d18c46",
      secondary: "#7fb6d8",
      shadow: "rgba(126, 72, 36, 0.3)",
      surface: "rgba(255, 244, 223, 0.78)",
      glow: "rgba(225, 156, 83, 0.34)",
      particle: "rgba(255, 248, 230, 0.74)",
    },
  },
  {
    id: "palace-of-earth-spirits",
    label: "地灵殿",
    subtitle: "旧地狱的地砖下，余火还在看人心",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/palace-of-earth-spirits-scene-v3.png",
    ritualAssets: buildRitualAssets("expanded", "palace-of-earth-spirits"),
    ritualImage: "/images/generated-themes/expanded/rituals/palace-of-earth-spirits-ritual-kit-v1.png",
    description: "旧地狱的热从地砖下透上来，房间深处安静得像有人刚读完你的心。第三只眼的纹样轻轻张开，签意从余火里浮出。",
    cardDescription: "透光方砖忽明忽暗，心读签匣在旧地狱余火里醒来。",
    cornerLabel: "地底心签",
    animationPlan: "心读余火签",
    ritualPlan: {
      tool: "心读签匣：素黑木匣配一个简洁第三只眼纹样，旁边只留一枚小鸟纹地砖作识别。",
      paper: "地底心签：暗红紫和纸，边缘略暖，纸背用少量方砖光影暗示旧地狱。",
      reveal: "读心显影：签纸先浮出模糊心音，第三只眼纹样轻轻闭合又张开，文字像从地砖下的余火里透上来。",
      ambientMotion: "少量透光方砖忽明忽暗，两三点怨灵光贴地游动，房间深处传来无访客的空回声。",
      sound: "低频地热、远处炉火、怨灵轻鸣和轻微木地板声，整体封闭、向内、略带压迫感。",
      assetPrompt:
        "干净日式二次元游戏背景，风格与现有 generated-themes 场景保持一致：地灵殿封闭室内大堂、简单柱廊、方砖地面、少量透光地砖、旧地狱余火、两三处怨灵光点、一个素黑心读签匣与第三只眼纹样。少道具、少纹理、低复杂度、可放 UI 文案。无角色，无文字，不要红魔馆外景，不要地狱城堡，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：地灵殿位于旧地狱中心，是古明地觉居住的大型洋馆，其下方为灼热地狱遗址与核聚变炉。",
      "THBWiki：地灵殿因读心能力几乎没有访客，但有大量宠物、怨灵管理语境。",
      "THBWiki：地灵殿四面有深浅交错方砖和彩色透光砖，图案疑似取自八咫乌，后续图要优先使用室内地砖与余火而非外部城堡。",
    ],
    visual: {
      ink: "#fff0ec",
      accent: "#b74758",
      secondary: "#7e63b8",
      shadow: "rgba(51, 26, 48, 0.42)",
      surface: "rgba(58, 32, 53, 0.68)",
      glow: "rgba(210, 72, 88, 0.3)",
      particle: "rgba(244, 190, 208, 0.68)",
    },
  },
  {
    id: "sanzu-river",
    label: "三途川",
    subtitle: "河雾从彼岸花边升起",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/sanzu-river-scene.png",
    ritualAssets: buildRitualAssets("expanded", "sanzu-river"),
    ritualImage: "/images/generated-themes/expanded/rituals/sanzu-river-ritual-kit-v1.png",
    description: "河上没有风，只有船桨把雾轻轻拨开。三途川的签纸先映在水面，再从船沿浮起，像一枚被摆渡钱换来的提醒。",
    cardDescription: "渡船签盒贴着河雾，灰蓝短签从水影里靠岸。",
    cornerLabel: "渡河雾签",
    animationPlan: "河雾渡签",
    ritualPlan: {
      tool: "渡船签盒：一只朴素小木盒放在无帆渡船边，旁边是一枚旧船桨和几枚摆渡钱。",
      paper: "河雾渡签：灰蓝短签纸，纸面像被河雾润湿，边缘有彼岸花的浅红印。",
      reveal: "雾面显签：签纸先倒映在水面，再从雾里浮到船沿，文字像被慢水一点点送上岸。",
      ambientMotion: "浓雾缓慢漂移，水面几乎无波，远处尖石上的苔光闪一下，河里有古代鱼影掠过。",
      sound: "极轻船桨拨水、摆渡钱碰木盒、远处死神歌声的残响；整体安静到近乎没有风。",
      assetPrompt:
        "明亮日式二次元游戏资产，三途河抽签仪式道具：无帆朴素渡船边的小木签盒、旧船桨、几枚摆渡钱、灰蓝河雾短签纸、彼岸花浅红印、平静水面和少量雾气。干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：三途河分割此岸与彼岸，亡者乘坐死神的船渡河，小野塚小町是常见摆渡人。",
      "THBWiki：三途河水流极慢、几乎无声、永远无风，河上有浓雾、发光雾点和长苔尖石。",
      "THBWiki：渡船朴素无帆，全靠死神手摇船桨；摆渡钱会影响三途河宽度。",
    ],
    visual: {
      ink: "#f5fbff",
      accent: "#4f9bc4",
      secondary: "#dd6b76",
      shadow: "rgba(32, 77, 101, 0.34)",
      surface: "rgba(229, 246, 255, 0.76)",
      glow: "rgba(98, 174, 207, 0.34)",
      particle: "rgba(238, 250, 255, 0.74)",
    },
  },
  {
    id: "misty-lake",
    label: "雾之湖",
    subtitle: "湖雾在水纹上慢慢散开",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/misty-lake-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "misty-lake"),
    ritualImage: "/images/generated-themes/expanded/rituals/misty-lake-ritual-kit-v1.png",
    description: "雾从湖面贴着水纹散开，薄冰在托盘边缘轻轻响。偶尔有妖精光点从冷雾里飞过，把短签照得清清亮亮。",
    cardDescription: "湖雾推开水纹，半透明短签像薄冰一样浮出。",
    cornerLabel: "湖畔冰雾签",
    animationPlan: "冰雾水纹签",
    ritualPlan: {
      tool: "湖雾冰晶签盘：浅木托盘浮在湖边石上，托盘边缘结着薄冰，旁边有一颗妖精光点。",
      paper: "冰雾短签：浅蓝半透明短签纸，纸背有水纹和小冰晶压印。",
      reveal: "水纹推签：湖雾先盖住托盘，水纹从中心扩开，签纸像薄冰一样浮出并逐渐变清楚。",
      ambientMotion: "湖面雾气横向流动，落叶轻漂，偶尔有小冰晶从画面边缘飞过，远处红馆轮廓只留一点影。",
      sound: "清水轻拍湖岸、冰晶细碎声、妖精光点掠过的轻响，清爽但略冷。",
      assetPrompt:
        "明亮日式二次元游戏资产，雾之湖抽签仪式道具：湖边石上的浅木托盘、薄冰边缘、浅蓝半透明短签纸、水纹、少量冰晶、一个小妖精光点和低雾。干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：雾之湖位于妖怪之山山脚，白天被浓雾覆盖，视界差且寒冷。",
      "THBWiki：雾之湖湖水清澈、湖上有雾气，湖畔有琪露诺、大妖精活动，若鹭姬居住在湖中。",
      "THBWiki：红魔馆位于雾之湖附近，后续画面可远景暗示但不应抢走湖雾主题。",
    ],
    visual: {
      ink: "#f1fbff",
      accent: "#60b9df",
      secondary: "#a6d9ff",
      shadow: "rgba(43, 104, 130, 0.28)",
      surface: "rgba(229, 248, 255, 0.78)",
      glow: "rgba(112, 200, 232, 0.34)",
      particle: "rgba(240, 252, 255, 0.78)",
    },
  },
  {
    id: "human-village",
    label: "人间之里",
    subtitle: "店招与布告把日常签意照亮",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/human-village-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "human-village"),
    ritualImage: "/images/generated-themes/expanded/rituals/human-village-ritual-kit-v1.png",
    description: "店招在巷口轻轻晃着，布告纸角被晚风掀起。人间之里的签藏在小木抽屉里，带一点账册墨味，也带一点刚有人走过的热闹。",
    cardDescription: "灯笼照着纸签抽屉，街风把日常签翻到正面。",
    cornerLabel: "街巷日常签",
    animationPlan: "街灯纸签",
    ritualPlan: {
      tool: "街巷纸签抽屉：低矮店铺门口的小木抽屉，旁边放账册、旧布告和一盏暖色灯笼。",
      paper: "日常街签：米白短签纸，边角像被店铺账册压过，盖有淡淡店印与小路纹。",
      reveal: "抽屉滑开揭签：灯笼先轻晃，纸签从木抽屉里露出半截，再被街风翻到正面。",
      ambientMotion: "布告纸角轻动、远处门帘掀起、巷口有一瞬刚离开的影子，整体保持人类村落的生活感。",
      sound: "木抽屉滑动、店招轻响、远处脚步和低声寒暄，声音亲近、日常，不做神社铃声。",
      assetPrompt:
        "明亮日式二次元游戏资产，人间之里日常街巷抽签仪式道具：低矮店铺门口的小木纸签抽屉、暖色灯笼、旧布告、店招、账册、米白短签纸和街风纸角，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：人类村落是幻想乡人类主要居住地，包含街道、商铺、民居、村口、农田和小道等日常空间。",
      "THBWiki：人类村落相关场景可延伸到铃奈庵、鲵吞亭、寺子屋等人类生活据点。",
      "候选图 v2 强化了店招、布告和有人刚离开的街巷感，适合作为日常街巷签而非观光街景。",
    ],
    visual: {
      ink: "#fff8ef",
      accent: "#d58a54",
      secondary: "#75b7b1",
      shadow: "rgba(132, 78, 44, 0.3)",
      surface: "rgba(255, 242, 224, 0.78)",
      glow: "rgba(225, 146, 86, 0.34)",
      particle: "rgba(255, 248, 235, 0.76)",
    },
  },
  {
    id: "sunflower-field",
    label: "向日葵田",
    subtitle: "花海里的影子比阳光慢半拍",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/sunflower-field-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "sunflower-field"),
    ritualImage: "/images/generated-themes/expanded/rituals/sunflower-field-ritual-kit-v1.png",
    description: "向日葵把脸转向阳光，地上的影子却慢了半拍。旧木牌旁的小签箱自己开了一线，花瓣把金色短签送出来。",
    cardDescription: "阳伞投下错位花影，淡金短签随花瓣升起。",
    cornerLabel: "花田异变签",
    animationPlan: "花影季节签",
    ritualPlan: {
      tool: "花田签箱与阳伞：旧木牌下的小签箱，箱盖被阳光晒亮，旁边立一把偏旧的花田阳伞。",
      paper: "金色季节签：淡金短签纸，纸背压有向日葵花盘纹和很浅的伞影。",
      reveal: "花影偏移揭签：风吹花海时签箱打开，签纸随花瓣升起，地面影子慢半拍后才对齐。",
      ambientMotion: "向日葵轻摆、花瓣从前景掠过、旧木牌投下略微不合常理的影子，阳光明亮但保留异变感。",
      sound: "夏风穿过花盘、木牌轻响、纸签被风掀起的细声，远处可以有很轻的伞柄碰木箱声。",
      assetPrompt:
        "明亮日式二次元游戏资产，向日葵田季节异变抽签仪式道具：旧木牌、小签箱、偏旧阳伞、淡金短签纸、向日葵花瓣、轻微错位的影子，干净分层构图，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：太阳花田是幻想乡深处的向日葵花田，是花之异变相关舞台意象之一。",
      "THBWiki / Touhou Wiki：风见幽香与花、花朵操纵和太阳花田意象高度相关，可转化为阳伞、花盘、花影和季节异变感。",
      "候选图 v2 已加入旧木牌、伞、签箱和轻微异变影子，适合作为季节活动候选而非普通花田宣传图。",
    ],
    visual: {
      ink: "#fffbea",
      accent: "#d9a928",
      secondary: "#7dbf75",
      shadow: "rgba(132, 99, 26, 0.28)",
      surface: "rgba(255, 248, 215, 0.78)",
      glow: "rgba(230, 188, 70, 0.34)",
      particle: "rgba(255, 252, 221, 0.78)",
    },
  },
  {
    id: "divine-spirit-mausoleum",
    label: "神灵庙",
    subtitle: "仙界道场的琉璃瓦下，灵光沿方砖归位",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/divine-spirit-mausoleum-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "divine-spirit-mausoleum"),
    ritualImage: "/images/generated-themes/expanded/rituals/divine-spirit-mausoleum-ritual-kit-v1.png",
    description: "仙界的石阶把脚步声收得很轻，红柱和琉璃瓦在灵光里发亮。铜铃一响，道符沿方砖归位，青白灵签从供案上竖起。",
    cardDescription: "铜铃唤起道符光阵，青白灵签在八角影中点亮。",
    cornerLabel: "仙界灵签",
    animationPlan: "道符灵光签",
    ritualPlan: {
      tool: "参庙签台：简洁供案配玉笏、铜铃和几张无字道教符，重点让石阶与八角塔说话。",
      paper: "仙界灵签：青白符纸配少量金色边线，纸面只保留简洁云纹和几颗灵光。",
      reveal: "符光归位：道符沿方砖广场排成简单八角形，铜铃一响，灵签从供案上竖起并逐段点亮签意。",
      ambientMotion: "屋檐金光轻闪、灯笼慢摆、少量青绿色神灵粒子沿石阶上升，整体保持干净留白。",
      sound: "细铜铃、香火轻响、石阶回音和极轻的道教法器声，整体明亮、庄严、带一点仙界错位感。",
      assetPrompt:
        "干净日式二次元游戏背景，风格与现有 generated-themes 场景保持一致：神灵庙仙界道场、直向石阶、简洁方砖广场、上翘檐、红柱、金色屋檐、两座八角侧塔、少量青绿色神灵粒子，前景只放简单供案、铜铃和几张无字道教符。少道具、少纹理、低复杂度、可放 UI 文案。无角色，无文字，不要普通神社鸟居，不要泛用森林神庙，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：神灵庙是丰聪耳神子在仙界中的道场，物部布都、苏我屠自古、霍青娥等也在此居住。",
      "THBWiki：神灵庙具有三层上翘房檐、龙凤瑞兽、彩绘红柱、金色琉璃瓦、两侧八角塔和方砖广场。",
      "THBWiki：梦殿大祀庙入口形似道观大门，并有道教神仙绘画；神灵庙相关图要优先强化道教庙观与仙界感。",
    ],
    visual: {
      ink: "#f7fff5",
      accent: "#49a987",
      secondary: "#d4b853",
      shadow: "rgba(33, 82, 73, 0.32)",
      surface: "rgba(224, 250, 238, 0.78)",
      glow: "rgba(89, 204, 164, 0.34)",
      particle: "rgba(238, 255, 244, 0.8)",
    },
  },
  {
    id: "nameless-hill",
    label: "无名之丘",
    subtitle: "荒野风声把铃兰影子吹远",
    status: "locked",
    sceneImage: "/images/generated-themes/expanded/nameless-hill-scene-v2.png",
    ritualAssets: buildRitualAssets("expanded", "nameless-hill"),
    ritualImage: "/images/generated-themes/expanded/rituals/nameless-hill-ritual-kit-v1.png",
    description: "山丘上几乎没有风，铃兰的影子贴着薄雾。没有标签的小玻璃瓶半埋在草间，签纸慢慢滑出，像终于想起自己的名字。",
    cardDescription: "静雾从无名签瓶里升起，灰白短签最后显出字迹。",
    cornerLabel: "铃兰无名签",
    animationPlan: "静雾铃兰签",
    ritualPlan: {
      tool: "铃兰无名签瓶：一只没有标签的小玻璃瓶半埋在山丘草间，瓶口系着褪色细绳。",
      paper: "无名铃兰签：灰白短签纸，纸角有淡绿色铃兰影，留出一块像被擦掉名字的空白。",
      reveal: "静雾开瓶：没有风，瓶中薄雾自行升起，签纸缓慢滑出，空白处最后才显出签意。",
      ambientMotion: "铃兰几乎不摆动，冷雾贴地，远处山坡光线很低，偶尔有幽灵般的小光点经过。",
      sound: "近乎无声，只保留玻璃轻碰、草叶细响和低低耳鸣感，突出无风与被遗忘的气氛。",
      assetPrompt:
        "明亮但克制的日式二次元游戏资产，无名之丘抽签仪式道具：阴冷山丘草间的小玻璃瓶、褪色细绳、灰白短签纸、淡绿色铃兰影、贴地薄雾和少量幽灵光点。干净分层构图，少纹理，无文字，无角色，不使用真实照片。",
    },
    sourceNotes: [
      "THBWiki：无名之丘位于妖怪之山对面，山丘中腹有大量铃兰田，日照不强、气温偏低且有毒气息。",
      "THBWiki：梅蒂欣·梅兰可莉诞生并居住于无名之丘，她是被丢弃在铃兰田里的人偶化作的妖怪。",
      "THBWiki：无名之丘有被遗忘和无风的设定，仪式应避免普通荒野风声，改用静雾、玻璃瓶与铃兰毒意。",
    ],
    visual: {
      ink: "#f9f7ef",
      accent: "#8d9870",
      secondary: "#c8b78a",
      shadow: "rgba(77, 86, 60, 0.28)",
      surface: "rgba(243, 240, 224, 0.78)",
      glow: "rgba(151, 164, 118, 0.3)",
      particle: "rgba(251, 249, 239, 0.74)",
    },
  },
];

function getRouteTextTone(sceneId: OmamoriRouteId): OmamoriRouteConfig["textTone"] {
  if (sceneId === "scarlet" || sceneId === "palace-of-earth-spirits") {
    return "mansion";
  }

  if (
    sceneId === "eientei" ||
    sceneId === "hakugyokurou" ||
    sceneId === "sanzu-river" ||
    sceneId === "misty-lake" ||
    sceneId === "nameless-hill"
  ) {
    return "moon";
  }

  return "shrine";
}

const EXPANDED_ROUTE_COPY_LABELS: Record<Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>, OmamoriRouteConfig["copyLabels"]> = {
  "moriya-shrine": {
    heading: "山上风祝签",
    quote: "风中所示",
    summary: "签意",
    advice: "守矢指引",
    luckyColor: "今日风色",
    luckyItem: "随身纸垂",
    motif: "注连纹样",
    rare: "奇迹回响",
    channel: "山风签路",
    inspiration: "风祝手记",
  },
  hakugyokurou: {
    heading: "幽冥樱签",
    quote: "花下所示",
    summary: "签意",
    advice: "白玉楼短笺",
    luckyColor: "今日樱色",
    luckyItem: "随身花瓣",
    motif: "冥樱纹样",
    rare: "幽明回响",
    channel: "樱庭签路",
    inspiration: "庭师记事",
  },
  "forest-of-magic": {
    heading: "森林魔导签",
    quote: "书页所示",
    summary: "签意",
    advice: "魔法森林便签",
    luckyColor: "今日星屑",
    luckyItem: "随身玻璃瓶",
    motif: "蘑菇星纹",
    rare: "魔力回响",
    channel: "魔导签路",
    inspiration: "书页批注",
  },
  "myouren-temple": {
    heading: "莲灯寺签",
    quote: "经卷所示",
    summary: "签意",
    advice: "命莲寺短偈",
    luckyColor: "今日灯色",
    luckyItem: "随身莲纹",
    motif: "莲花纹样",
    rare: "法会回响",
    channel: "寺灯签路",
    inspiration: "经卷旁注",
  },
  "palace-of-earth-spirits": {
    heading: "地底心签",
    quote: "心音所示",
    summary: "签意",
    advice: "地灵殿低语",
    luckyColor: "今日余火",
    luckyItem: "随身小钥",
    motif: "第三眼纹",
    rare: "读心回响",
    channel: "旧地狱签路",
    inspiration: "心读记录",
  },
  "sanzu-river": {
    heading: "渡河雾签",
    quote: "水影所示",
    summary: "签意",
    advice: "三途川渡语",
    luckyColor: "今日河雾",
    luckyItem: "随身渡钱",
    motif: "彼岸花纹",
    rare: "彼岸回响",
    channel: "渡河签路",
    inspiration: "船沿记号",
  },
  "misty-lake": {
    heading: "湖畔冰雾签",
    quote: "水纹所示",
    summary: "签意",
    advice: "雾之湖短句",
    luckyColor: "今日冰蓝",
    luckyItem: "随身冰晶",
    motif: "湖雾纹样",
    rare: "妖精回响",
    channel: "冰雾签路",
    inspiration: "湖面涟漪",
  },
  "human-village": {
    heading: "街巷日常签",
    quote: "灯下所示",
    summary: "签意",
    advice: "人间之里便条",
    luckyColor: "今日灯笼色",
    luckyItem: "随身店印",
    motif: "街巷纹样",
    rare: "人声回响",
    channel: "里巷签路",
    inspiration: "布告纸角",
  },
  "sunflower-field": {
    heading: "花田异变签",
    quote: "花影所示",
    summary: "签意",
    advice: "向日葵田耳语",
    luckyColor: "今日葵金",
    luckyItem: "随身花瓣",
    motif: "花盘纹样",
    rare: "季节回响",
    channel: "花影签路",
    inspiration: "阳伞投影",
  },
  "divine-spirit-mausoleum": {
    heading: "仙界灵签",
    quote: "符光所示",
    summary: "签意",
    advice: "神灵庙符语",
    luckyColor: "今日青白",
    luckyItem: "随身铜铃",
    motif: "八角光阵",
    rare: "神灵回响",
    channel: "仙界签路",
    inspiration: "方砖灵光",
  },
  "nameless-hill": {
    heading: "铃兰无名签",
    quote: "静雾所示",
    summary: "签意",
    advice: "无名之丘低声",
    luckyColor: "今日雾白",
    luckyItem: "随身细绳",
    motif: "铃兰影纹",
    rare: "遗忘回响",
    channel: "无名签路",
    inspiration: "空白标签",
  },
};

const EXPANDED_ROUTE_STAGE_COPY: Record<
  Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>,
  OmamoriRouteConfig["stage"]
> = {
  "moriya-shrine": {
    eyebrow: "山上参拜",
    title: "风祝铃响起，卷轴签顺着山风展开",
    description: "轻触铃绳，等注连绳下的纸垂摆过一阵。守矢神社会把今日的奇迹收进一枚淡绿神签里。",
    ringing: "风祝铃正沿妖怪之山传开",
    shaking: "注连绳签架正在迎风重排签意",
    revealing: "卷轴签正被山风展开",
    rareNotice: "奇迹回响已出现",
    favoriteAdded: "已收进本地山风签册",
    favoriteRemoved: "已把这张风祝签放回守矢参道",
  },
  hakugyokurou: {
    eyebrow: "樱庭启签",
    title: "樱瓣落下前，冥签会先亮起一线",
    description: "轻触庭铃，让石阶上的薄雾慢下来。白玉楼的签意不会吵醒春雪，只会在花影里露出一点轮廓。",
    ringing: "樱庭铃声正穿过白玉楼回廊",
    shaking: "半透明冥签正在花雾里成形",
    revealing: "冥签正随刀光展开",
    rareNotice: "幽明回响已出现",
    favoriteAdded: "已收进本地樱签册",
    favoriteRemoved: "已把这张冥签放回白玉楼石阶",
  },
  "forest-of-magic": {
    eyebrow: "林中翻书",
    title: "魔导书翻到空白页，星屑把签纸托起",
    description: "轻触书脊，别惊动太多蘑菇。魔法森林会用一点潮气、一点星粉，给今天写出不太循规蹈矩的答案。",
    ringing: "小玻璃瓶正发出细响",
    shaking: "魔导书页正在重排今日签意",
    revealing: "星屑纸符正从页缝浮起",
    rareNotice: "魔力回响已出现",
    favoriteAdded: "已收进本地魔导签册",
    favoriteRemoved: "已把这张纸符放回树根书页",
  },
  "myouren-temple": {
    eyebrow: "寺灯问签",
    title: "寺灯亮起，经卷把莲纹短签送出",
    description: "轻触木鱼旁的签台，听经卷纸面慢慢展开。命莲寺给出的提醒通常不急，但会落得很稳。",
    ringing: "寺灯铃声正沿参拜道亮起",
    shaking: "莲纹经卷正在展开今日签意",
    revealing: "寺签正从卷轴内侧滑出",
    rareNotice: "法会回响已出现",
    favoriteAdded: "已收进本地莲灯签册",
    favoriteRemoved: "已把这张寺签放回命莲寺灯下",
  },
  "palace-of-earth-spirits": {
    eyebrow: "地底读心",
    title: "第三只眼轻轻张开，余火从方砖下透出",
    description: "轻触心读签匣，先别急着移开视线。地灵殿会把没说出口的念头像地热一样慢慢托上来。",
    ringing: "地底回声正贴着方砖传来",
    shaking: "心读签匣正在听取今日心音",
    revealing: "地底心签正从余火里显影",
    rareNotice: "读心回响已出现",
    favoriteAdded: "已收进本地地底签册",
    favoriteRemoved: "已把这张心签放回旧地狱余火",
  },
  "sanzu-river": {
    eyebrow: "河雾渡签",
    title: "摆渡钱轻响，签纸从水影里靠岸",
    description: "轻触船沿的小木盒，等河雾让出一条窄路。三途川的签不催行程，只提醒你该带走哪一句。",
    ringing: "摆渡钱正轻碰渡船签盒",
    shaking: "河雾短签正在水面倒影里重排",
    revealing: "渡河签正从雾面浮起",
    rareNotice: "彼岸回响已出现",
    favoriteAdded: "已收进本地渡河签册",
    favoriteRemoved: "已把这张雾签放回三途川船沿",
  },
  "misty-lake": {
    eyebrow: "湖畔启签",
    title: "湖雾推开水纹，冰雾短签浮出托盘",
    description: "轻触冰雾签盘，让薄冰先响一下。雾之湖会把今日的提醒冻得清亮，再交到你手里。",
    ringing: "冰雾铃声正掠过湖面",
    shaking: "水纹正在托盘里重排今日签意",
    revealing: "冰雾短签正在变得清楚",
    rareNotice: "妖精回响已出现",
    favoriteAdded: "已收进本地湖雾签册",
    favoriteRemoved: "已把这张短签放回雾之湖水纹",
  },
  "human-village": {
    eyebrow: "街巷问签",
    title: "木抽屉轻轻滑开，灯笼把签纸照亮",
    description: "轻触店门口的小抽屉，等布告纸角安静下来。人间之里的签像一句路过时听见的叮嘱，朴素，但有用。",
    ringing: "街灯铃声正从巷口传来",
    shaking: "纸签抽屉正在翻找今日签意",
    revealing: "街巷日常签正被晚风翻开",
    rareNotice: "人声回响已出现",
    favoriteAdded: "已收进本地街巷签册",
    favoriteRemoved: "已把这张街签放回人间之里抽屉",
  },
  "sunflower-field": {
    eyebrow: "花田听风",
    title: "阳伞影子慢半拍，金色短签随花瓣升起",
    description: "轻触旧木牌下的小签箱，别急着判断影子的方向。向日葵田会把答案晒得很亮，也留一点异变的余味。",
    ringing: "花田铃声正穿过向日葵花盘",
    shaking: "旧木签箱正在花影里重排签意",
    revealing: "金色季节签正随花瓣升起",
    rareNotice: "季节回响已出现",
    favoriteAdded: "已收进本地花影签册",
    favoriteRemoved: "已把这张花田签放回旧木牌下",
  },
  "divine-spirit-mausoleum": {
    eyebrow: "仙界参庙",
    title: "铜铃一响，道符沿方砖排成光阵",
    description: "轻触供案前的铜铃，让石阶回音停在檐下。神灵庙的签意会从青白灵光里竖起，像一句端正的诏令。",
    ringing: "灵庙铜铃正沿石阶回响",
    shaking: "道符光阵正在归位今日签意",
    revealing: "仙界灵签正从供案上点亮",
    rareNotice: "神灵回响已出现",
    favoriteAdded: "已收进本地灵庙签册",
    favoriteRemoved: "已把这张灵签放回神灵庙供案",
  },
  "nameless-hill": {
    eyebrow: "静雾启瓶",
    title: "没有风，铃兰影里仍滑出一张无名签",
    description: "轻触半埋在草间的小玻璃瓶。无名之丘的签来得很慢，像一件被忘记太久的事，终于愿意开口。",
    ringing: "无名铃声几乎被薄雾吞没",
    shaking: "玻璃签瓶正在静雾里唤回签意",
    revealing: "铃兰无名签正慢慢显字",
    rareNotice: "遗忘回响已出现",
    favoriteAdded: "已收进本地无名签册",
    favoriteRemoved: "已把这张无名签放回铃兰薄雾",
  },
};

function createExpandedRouteConfig(scene: SceneCandidate): OmamoriRouteConfig {
  const sceneId = scene.id as OmamoriRouteId;
  const ritualAssets = scene.ritualAssets ?? buildRitualAssets("expanded", scene.id);
  const expandedSceneId = sceneId as Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>;

  return {
    id: sceneId,
    label: scene.label,
    shortLabel: scene.label,
    subtitle: scene.subtitle,
    description: scene.description,
    cardDescription: scene.cardDescription,
    cornerLabel: scene.cornerLabel,
    enterLabel: `进入${scene.label}`,
    drawLabel: `抽取${scene.label}签文`,
    revisitLabel: `展开${scene.label}签文`,
    backLabel: "重新选择入口",
    statusIdle: `${scene.label}今日尚未启签`,
    resultTitle: `${scene.label}签文`,
    shareFrom: scene.label,
    sceneImage: scene.sceneImage,
    ritualImage: scene.ritualImage,
    textureImage: "/images/textures/washi-noise.svg",
    ritualAssets,
    textTone: getRouteTextTone(sceneId),
    visual: scene.visual,
    copyLabels: EXPANDED_ROUTE_COPY_LABELS[expandedSceneId],
    stage: EXPANDED_ROUTE_STAGE_COPY[expandedSceneId],
  };
}

const EXPANDED_OMAMORI_ROUTES = Object.fromEntries(
  SCENE_BLUEPRINTS
    .filter((scene) => !scene.routeId)
    .map((scene) => [scene.id, createExpandedRouteConfig(scene)]),
) as Record<Exclude<OmamoriRouteId, keyof typeof BASE_OMAMORI_ROUTES>, OmamoriRouteConfig>;

export const OMAMORI_ROUTES = {
  ...BASE_OMAMORI_ROUTES,
  ...EXPANDED_OMAMORI_ROUTES,
} satisfies Record<OmamoriRouteId, OmamoriRouteConfig>;

export const OMAMORI_ROUTE_LIST = OMAMORI_ROUTE_IDS.map((routeId) => OMAMORI_ROUTES[routeId]);

export const SCENE_CANDIDATES: SceneCandidate[] = SCENE_BLUEPRINTS.map((scene) => {
  const routeId = (scene.routeId ?? scene.id) as OmamoriRouteId;
  const route = OMAMORI_ROUTES[routeId];

  return {
    ...scene,
    status: "active",
    routeId,
    cornerLabel: route.cornerLabel,
    ritualAssets: route.ritualAssets,
    visual: route.visual,
  };
});

export function isOmamoriRouteId(value: unknown): value is OmamoriRouteId {
  return typeof value === "string" && OMAMORI_ROUTE_IDS.includes(value as OmamoriRouteId);
}

export function getOmamoriRoute(routeId: OmamoriRouteId | undefined | null): OmamoriRouteConfig {
  return routeId && OMAMORI_ROUTES[routeId] ? OMAMORI_ROUTES[routeId] : OMAMORI_ROUTES.hakurei;
}

export const DRAW_TIMINGS = {
  closed: 780,
  shaking: 1320,
  emerging: 2600,
  open: 0,
  flash: 800,
  reducedBell: 220,
  reducedTube: 280,
  reducedEmerging: 360,
  reducedOpen: 0,
  reducedFlash: 220,
} as const;
